### ISSUE TITLE
Cleverbot bug

### ISSUE THREAD

**Issue by Portanna** [iBlitzkriegi/Vixio#10]
Cleverbot API does not work. The cleverbot response is always the same as the request.

Example:
Me: $dolan say something
Bot: say something

**Syntax**

```
on guild message receive seen by "Dolan":
    set {_args::*} to event-string split at " "
    set {_command} to {_args::1}
    remove {_args::1} from {_args::*}
    if {_command} starts with "$dolan":
        set {_string} to event-string
        replace all "$dolan " with "" in {_string}
        reply with "%cleverbot response for {_string}%" 
```

**Error**

[15:36:15 WARN]: java.io.IOException: Server returned HTTP response code: 401 for URL: http://www.cleverbot.com/webservicemin?uc=777&botapi=chatterbotapi

**Comment by tutur1004** [comment]
You forgot to say, the bot replay with %{_string}% exactly

**Comment by Portanna** [comment]
Yes but that's a direct consequence of the API not working, as the request is unauthorized. (i'm editing the message anyways)

**Comment by iBlitzkriegi** [comment]
Fixed in latest build. Added configuration file to add a clever bot api key.
