### ISSUE TITLE
syntax conflict (ID's)

### ISSUE THREAD

**Issue by HardstylesDev** [iBlitzkriegi/Vixio#105]
Using the `set {_var} to id of {_guild}` in a function, seems to break though. My code:

```
function shit(content: string, guild: guild, channel: channel, message: message):
	set {_id} to id of {_guild}
	set {_id2} to {_guild}.getId()
	
	send "Variable {_id}: %{_id}%" to {_channel} with {@bot}
	send "Variable {_id2}: %{_id2}%" to {_channel} with {@bot}	

discord command testthis:
	trigger:
		shit("xd", event-guild, event-channel, event-message)
```
It will reply with the old <none>.
Using {_guild}.getId() works like a charm though.

**Comment by Pikachu920** [comment]
skellett issue

**Comment by iBlitzkriegi** [comment]
Yeah, I think I'm gonna just go ahead and make it discord if of, tired of stupid conflicts

**Comment by Angel-0** [comment]
If you want to get totally rid of this conflict between Skellett and Vixio, go in `SyntaxToggles.yml` in Skellett folder, search `EntityID` and disable it. 😉

**Comment by iBlitzkriegi** [comment]
This was fixed when id of was changed to discord id of.
