### ISSUE TITLE
Changing Volume in Vixio crashes server.

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#107]
Hi, when I change the volume of my bot using the syntax `set the volume of event-bot to arg-1` it will not update the volume, and then if I wait a moment, the server will then throw an error, and the bot stops playing ( I can tell from the green ring dissapearing ).

Here is my error here: https://hastebin.com/anobewolaj.shell
Hopefully this can be fixed, Thanks Ender.

**Comment by EnderDev** [comment]
Here's a video of what happens:

https://cdn.ender.site/videos/error.mp4

I've talked to the hosting people, and they said it's the plugin's issue.

**Comment by iBlitzkriegi** [comment]
The first error is completely unrelated. You attempt to interact with a message that JDA can no longer find. I.E deleted/can't view it anymore, etc.

**Comment by iBlitzkriegi** [comment]
I've contacted the Lavaplayer developer to see what he had to say about it, he said that the server is missing a necessary library. 
![image](https://user-images.githubusercontent.com/17624546/47327838-c1a50780-d63c-11e8-87e2-3c2603dd495e.png)

**Comment by EnderDev** [comment]
Alright, so I tell the server administrators to write that command yes?

**Comment by iBlitzkriegi** [comment]
The host will know what to do with the provided information.
