### ISSUE TITLE
Condition doesn't work

### ISSUE THREAD

**Issue by DJMax486** [iBlitzkriegi/Vixio#12]
The condition "if name of event-channel is "%{a variable}%" doesn't work
My exactly code line: (if name of event-channel is "%{diskordlink.channel.gestion}%":)
The error: "event-types.channel is not a slot (diskordlink3_6.sk, line 878: if name of event-channel..."

**Comment by iBlitzkriegi** [comment]
You are using the incorrect syntax. The syntax is `discord name of' not 'name of'. `name of` is a vanilla skript syntax.

**Comment by DJMax486** [comment]
I'll try this syntax.

**Comment by DJMax486** [comment]
OK, it's working.
Thanks.
Btw, the syntax wich I used was the syntax for Vixio 1.1.2 ^^

**Comment by iBlitzkriegi** [comment]
You can check the docs located here: http://vixio.space/docs/ for updated syntax!

**Comment by DJMax486** [comment]
Thanks you ! :D
