### ISSUE TITLE
Outdated Example

### ISSUE THREAD

**Issue by GamingGeek** [iBlitzkriegi/Vixio#124]
**Describe the bug**
Vixio butler example for `members of` is outdated

**To Reproduce**
1. Go to 'vixio' on discord
2. Go to #bot-testing
3. Type `.lookup members`
4. Click the `2` and read the example

**Expected behavior**
The example should have `discord members` instead of `members`

**Screenshots**
![image](https://user-images.githubusercontent.com/29981918/47942964-ebd3b080-deeb-11e8-8610-490e4cd22d40.png)

**Comment by iBlitzkriegi** [comment]
Fixed
