### ISSUE TITLE
[BUG] Avatar of returns null for default avatars.

### ISSUE THREAD

**Issue by iBlitzkriegi** [iBlitzkriegi/Vixio#125]
**Describe the bug**
The avatar of expression returns null if they have a default avatar.

**To Reproduce**
1. Login to a new account that only has it's default avatar
2. Call avatar of event-user, and see that it's null

**Expected behavior**
It should return the default avatar, seeing as that IS their avatar.

**Screenshots**
![image](https://user-images.githubusercontent.com/17624546/48161557-d6be9f00-e2a8-11e8-84e1-304c8d2b92e0.png)

**Additional context**
None needed

**Comment by EnderDev** [comment]
Not really a bug but okay, should happen in all libraries. If there isn't a default value if the avatars is null for example: "No avatar" or something.

**Comment by iBlitzkriegi** [comment]
No, it's definitely a bug. It's not up to me to decide how your error messages are displayed, and when you have no custom avatar and only your default one, that IS your avatar. It's annoying to have to use bloat code to figure out which to display. At the very least it needs to be returning legitimately null and not just the word null.
