### ISSUE TITLE
Can't get "discord name of %user%"

### ISSUE THREAD

**Issue by 4rnoP** [iBlitzkriegi/Vixio#13]
Hello,
If I use my account with Vixio, I can get information of players only from one guild, example:
```
on guild message seen by "Arno":
	#If message comes from guild "A"
	if event-guild is "XXXXX":
		#send the author and the message to another guild "B"
		send message "%discord name of event-user% » %event-string%" to channel "XXXXX" as "Arno"
```
if the event-user isn't also in the guild "B", the %discord name of event-user% results with "\<none>"...

**Comment by WheezyGold7931** [comment]
You need to be in the guild to pull the username

**Comment by iBlitzkriegi** [comment]
This issue seems to have been left at the last comment.
