### ISSUE TITLE
Issue When Editing the Voice Channel Name

### ISSUE THREAD

**Issue by Kuro001** [iBlitzkriegi/Vixio#134]
When I used this syntax to edit the name of a voice channel, where there were spaces now there were "-"
 -    `set name of event-channel to "x d"`

**Comment by Padlick01** [comment]
That isn't a bug of vixio. Thats Discord. You can't use spaces in names of channels.

**Comment by Angel-0** [comment]
> 
> 
> That isn't a bug. Thats Discord. You can't use spaces in names of channels.

False, you can use spaces in name of **voice** channels.

**Comment by Kuro001** [comment]
> That isn't a bug. Thats Discord. You can't use spaces in names of channels.
In the discord you can put names with spaces only in the voice channels and, my report, was about changing the name of the voice channels with spaces.
