### ISSUE TITLE
1.7.10 Support

### ISSUE THREAD

**Issue by Rubyliss** [iBlitzkriegi/Vixio#136]
**Is your feature request related to a problem? Please describe.**
Well this is pretty clear, make it work with the version 1.7.10 of MC

i can't say more thing about it ^^'

**Comment by iBlitzkriegi** [comment]
First of all, we will not go out of our way to support a version released 4 years ago. So if you can manage to get Skript working, and Vixio running then power to ya. But we wont provide support for something that ancient. 
If you can find a stable Skript version that works with 1.7.10, then nothing within Vixio will stop it from working on that version.
