### ISSUE TITLE
Discord command reload problem

### ISSUE THREAD

**Issue by Olyno** [iBlitzkriegi/Vixio#137]
**Describe the bug**
Discord commands are not reloaded correctly when a condition is above code.

**To Reproduce**

 1. Use this code:
```vb
discord command test:
	trigger:
		id of event-channel is "510206427248328704"
		broadcast "oh first"
```
 2. Change the id of the channel with another
 3. After use this code, change "first" with "second" in the broadcast
 4. Do ``/sk reload all`` in your console
 5. The command will tell you "oh first" instead of "oh second"

**Expected behavior**
This bug doesn't refresh/reload discord commands correctly when we use the command ``/sk reload all``

**Comment by AlexLew95** [comment]
Btw, this bug/problem is the same about all vixio stuff

**Comment by iBlitzkriegi** [comment]
Just as a note, this does not occur when you reload the skript normally with /skript reload skript.sk. This only occurs when you use skript reload all, which should be a relatively easy fix. Side-node, the condition in the code does not affect this outcome.

**Comment by iBlitzkriegi** [comment]
This has since been fixed; 
```
discord command test:
	trigger:
		reply with "oh first"
```
then changing it to 
```
discord command test:
	trigger:
		reply with "oh first2"
```
and running `/skript reload all` results in:
![image](https://user-images.githubusercontent.com/17624546/66145400-c3ab7080-e5d8-11e9-9e1f-2ecd495e73ab.png)
