### ISSUE TITLE
Outated example & description

### ISSUE THREAD

**Issue by Angel-0** [iBlitzkriegi/Vixio#138]
The example for `Member has role` [condition](https://github.com/iBlitzkriegi/Vixio/blob/master/src/main/java/me/iblitzkriegi/vixio/conditions/CondMemberRole.java) is outdated. Actually, it is:
```vb
discord command $role <member> <string>:
    trigger:
        if arg-1 has role named arg-2:
            reply with "%arg-1% does have a role named %arg-2%"
            stop
        reply with "%arg-1% does not have a role named %arg-2%"
```
However, it should be:

```vb
discord command $role <member> <string>:
    trigger:
        if arg-1 has role role named arg-2:
            reply with "%arg-1% does have a role named %arg-2%"
            stop
        reply with "%arg-1% does not have a role named %arg-2%"
```

Also, I've seen a wrong description for `ID of` [expression](https://github.com/iBlitzkriegi/Vixio/blob/master/src/main/java/me/iblitzkriegi/vixio/expressions/ExprId.java):
Actually is: `Get the ID of of any discord entity`
But should be `Get the ID of any discord entity`

**Comment by iBlitzkriegi** [comment]
The example is correct. There are four registered syntaxes, one of them being `%member% (has|have) [the] role [named] %string%`.
