### ISSUE TITLE
Clone Channel

### ISSUE THREAD

**Issue by SaltyMadrid** [iBlitzkriegi/Vixio#139]
**Is your feature request related to a problem? Please describe.**
I'm trying to clone a channel and delete the other (deleting is possible, cloning isn't tho)

**Describe the solution you'd like**
Add a `clone %channel% in %guild% with [new] name %string%` effect?

**Describe alternatives you've considered**
Taking exactly every single value of the previous channel and using the create scope and using these values. Didn't really work out great.

**Additional context**
Yeah idk it's just a clone channel effect lol

**Comment by AntoDB** [comment]
Nice suggestion to make a bot that opens tickets for support :p

**Comment by AlexLew95** [comment]
The syntax would be:
```vb
clone %channel% [in %guild%] [with [new] name %string%] [(with|as) %bot/string%] [and store (it|the channel) in %-objects%]
```
Where ``guild`` would be the event-guild if it's not precised, and the name the current channel's name, with of course the possibility to store the new channel

**Comment by iBlitzkriegi** [comment]
Added in https://github.com/iBlitzkriegi/Vixio/commit/c634fc27620f9a93836bd2c11e7640b3e37faf60
