### ISSUE TITLE
Loop issue

### ISSUE THREAD

**Issue by titustitus98** [iBlitzkriegi/Vixio#140]
here is my code:
`every hour:`
    `loop discord members of guild with id "330907956621344770":`
        `if {hourpoints::%loop member%} < 5:`
           `remove 1 from {points::%loop member%}`
            `set {hourpoints::%loop ember%}`
            `if {points::%loop member%} <= 0:`
                `set {points::%loop member%} to 0`
        `else set {hourpoints::%loop member%} to 0`

here is what i get when i reload this skript:
`03.12 13:10:32 [Server] ERROR Can't understand this loop: 'loop discord members of guild with id "330907956621344770"' (zlixerbutler.sk, line 50: loop discord members of guild with id "330907956621344770":')`

wwhat is the correct loop value that i have to use?

**Comment by iBlitzkriegi** [comment]
The GitHub is reserved for bug reports, suggestions and error reporting. This is to be handled in the Vixio Discord.
