### ISSUE TITLE
Cannot use nickname of "BotName" in event-guild in function

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#144]
**Describe the bug**
Can't use `nickname of "BotName" in event-guild`.

**To Reproduce**
1. Make a function
2. Return `nickname of "BotName" in guild with id {_guild}`, guild being one of the function params.

**Expected behavior**
Should behave like event-bot would.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Angel-0** [comment]
Not really a bug.

A type.string is not equal to a type.bot. You have to use this expression (below) if you want to get or set it through a function
```vbs
nickname of (({_string} parsed as bot) in {_guild})
```
