### ISSUE TITLE
Cannot seem to set the nickname of the bot to a value in a guild with id

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#146]
**Describe the bug**
Cannot seem to set `set the discord nickname of "BotName" parsed as bot in guild with id {_guild} to {_data}`, {_guild} being the guild ID, and {_data} being the string to set it to.

**To Reproduce**
1. Use this in a function
2. Set the variables
3. It doesn't set the nick.

**Expected behavior**
I expected it to simply set the nickname.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Angel-0** [comment]
Parsing problem. Use this instead:
```vb
set the discord nickname of ("BotName" parsed as bot) in guild with id {_guild} to {_data}
```

**Comment by EnderDev** [comment]
with the brackets?

**Comment by Angel-0** [comment]
Yes, it worked for map it should for you as well

**Comment by EnderDev** [comment]
Did not work: error is here: https://paste.ender.site/paste.php?id=1

**Comment by Angel-0** [comment]
I bet we simply forgot the `with "bot"` part 😂

**Comment by EnderDev** [comment]
you think?

**Comment by EnderDev** [comment]
legend
