### ISSUE TITLE
Cannot get name of track from URL string.

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#148]
**Describe the bug**
Cannot get name of track from URL string.

**To Reproduce**
1. set {_f} to "https://www.youtube.com/watch?v=k85hnRPqvMbE"
2. reply with "%name of {_f}%"
3. does not give name of url

**Expected behavior**
return the name of the youtube video

**Screenshots**
N/A

**Additional context**
N/A

**Comment by EnderDev** [comment]
So how do I do it

**Comment by AlexLew95** [comment]
@EnderDev the syntax ``name of %url%`` doesn't exist in vixio, use tracks to do that

**Comment by EnderDev** [comment]
ok
