### ISSUE TITLE
[Suggestion] Webhook-related things

### ISSUE THREAD

**Issue by KabanFriends** [iBlitzkriegi/Vixio#150]
Reason why I want to have them:
I just found a bot that sync text through multiple text channels and multiple servers and the interesting point was it uses Webhook for users when showing other server's text: 
![image](https://user-images.githubusercontent.com/45000995/50726733-9bc7d300-1154-11e9-9cf4-6e8ff29b4d85.png)
then I got interested in automated Webhooks but there's no webhook-related things in Vixio yet, so I'd like to have them in Vixio.

Things I want (at least):
Effect to create a new webhook
Effect to modify webhook (icons, names and other)

**Comment by EnderDev** [comment]
Just use reqn and skript-json, there is a whole documentation for Discord webhooks here. It has nothing to do with vixio. https://discordapp.com/developers/docs/resources/webhook

**Comment by Snow-Pyon** [comment]
@EnderDev what's the point of the addon then? You can use Reqn and skript-json for almost every feature it has, Discord's API is a RESTful API after all.

**Comment by KabanFriends** [comment]
I want to have webhook things in Vixio to use webhooks easier
I sometimes use reqn but it's quite hard for me

**Comment by GamingGeek** [comment]
> 
> 
> I want to have webhook things in Vixio to use webhooks easier
> I sometimes use reqn but it's quite hard for me

webhooks are basically just bots that you can send messages through using API requests. what's the point having webhook related features when you can make a proper bot do the exact same thing throug vixio?

**Comment by iBlitzkriegi** [comment]
This would really be left to those addons.
