### ISSUE TITLE
Error for no reason?

### ISSUE THREAD

**Issue by bolleboor** [iBlitzkriegi/Vixio#159]
**Describe the bug**
So, I get this error message and my bot stopped working.
https://gist.github.com/bolleboor/5b3bd19cfb435d49a8b77f12275f8a5d
And it's because of this code:
https://gist.github.com/bolleboor/9fb175909666f84621badbaa9eebb846
^^^^
is letting the player sit on a pig that is invincible.

**To Reproduce**
1. Create a command with that code.
2. Try to sit (sitting works fine)
3. the error appears in console and bot stopped working?

**Expected behavior**
I just expected it to be working just fine.

**Comment by iBlitzkriegi** [comment]
Duplicate issue
