### ISSUE TITLE
bot has permission ~ gots Error

### ISSUE THREAD

**Issue by BBLRDevelope** [iBlitzkriegi/Vixio#160]
**Describe the bug**
When vixio trying event-bot has permission.

**To Reproduce**
1. Create A Discord Command.
2. Add 'if event-bot has permission administrator in event-guild:'
3. And Execute a Command in Guild

**Expected behavior**
When executed guild's bot have administrator permission, it will get executed to another line.

**Screenshots**
None

**Code** (@ is tab)
if event-bot has permission administrator in event-guild:
@reply with "I have Administrator perms"
else:
@reply with "I dont have administrator perms"

**Error screenshots**
Bukkit: https://imgur.com/a/Xcwb39K

**Additional context**
None.

**Comment by GamingGeek** [comment]
why screenshots of the error and not just the error itself? Makes it kinda annoying. Also you could've just put the code in a codeblock and use tabs instead of @. Anyways, you need to remember that user's don't have permissions, members do...

**Comment by iBlitzkriegi** [comment]
As said, members have permissions, users do not.
