### ISSUE TITLE
Cancelling event on guild message

### ISSUE THREAD

**Issue by Minkizz** [iBlitzkriegi/Vixio#166]
Hello, I would like to cancel guild messages received for a private reason.
Can you add "cancel event" for on guild message received?
Or maybe an action "remove latest message"?
Thank you!

**Comment by AlexLew95** [comment]
You need **grab messages** and **delete them**. You can't cancel the event, but it can be a future feature.

**Comment by Minkizz** [comment]
how can I delete them?

**Comment by Minkizz** [comment]
Oh, also you live in France, me too!
Je suis français, réponds moi en français si tu veux!

**Comment by iBlitzkriegi** [comment]
Cancelling them would lead to issues for things like not specifying a bot and having multiple bots, wouldn't know with which bot to delete the message and would not be my place to decide one for you. You can use `delete event-message with event-bot` to delete the message.
