### ISSUE TITLE
[Help wanted] How to get private message

### ISSUE THREAD

**Issue by Minkizz** [iBlitzkriegi/Vixio#167]
Hello, I use the event "on private message received seen by %string", it works fine, but how to get the private message that has been sent?
Thank you for your help.

**Comment by GamingGeek** [comment]
Use the Vixio Butler bot instead of opening a github issue... (you can invite it to your own guild since you're muted in vixio)

**Comment by Minkizz** [comment]
what is the vixio butler bot?

**Comment by Minkizz** [comment]
oh yeah it's the bot with .lookup but i'm banned 🤣

**Comment by iBlitzkriegi** [comment]
The github is not to be used for help requests, but for feature requests and error reporting. The answer is `event-message` but this will be the only answer you find here.
