### ISSUE TITLE
ID of a stored message variable

### ISSUE THREAD

**Issue by KabanFriends** [iBlitzkriegi/Vixio#169]
"id of %message%" doesn't work for stored message variables. it just returns nothing or \<none\>.
script has no error and console did not get any error.

it should return the id of that stored message.

I need this for checking if a stored message _still_ exists on a channel

**Comment by AlexLew95** [comment]
What's your code?

**Comment by KabanFriends** [comment]
IMPORTANT SYNTAX:
`id of {{@BotID}.%{namelist.edit.guildid.%id of event-user%}%.%{namelist.edit.channelid.%id of event-user%}%.namelist.mid.%id of event-user%} to channel with id "555399883587321856" with event-bot`


First, I tried to get the ID of a stored message variable and use it to retrieve the message.
CODE OF THE FIRST ATTEMPT:
`retrieve message with id "%id of {{@BotID}.%{namelist.edit.guildid.%id of event-user%}%.%{namelist.edit.channelid.%id of event-user%}%.namelist.mid.%id of event-user%}%"

if last retrieved message is not set:
  <do something here>`
This code did not work, so I put `id of {{@BotID}.%{namelist.edit.guildid.%id of event-user%}%.%{namelist.edit.channelid.%id of event-user%}%.namelist.mid.%id of event-user%}` in a send message/broadcast effect and tested it. It said <none>.

Then after testing more, I realized sending ID of bot (without embedding it with percentage thingy) to discord server can display the ID of the stored message variable. So...
CODE OF THE SECOND ATTEMPT:
`send id of {{@BotID}.%{namelist.edit.guildid.%id of event-user%}%.%{namelist.edit.channelid.%id of event-user%}%.namelist.mid.%id of event-user%} to channel with id "555399883587321856" with event-bot

grab last 1 messages in channel with id "555399883587321856" and store them in {_grabbed::*}

set {_id} to "%contents of random object out of grabbed messages%"
retrieve message with id "%{_id}%"

if last retrieved message is not set:
  <do something here>`
555399883587321856 is a text channel for storing IDs temporary.
Now, I realized another problem of Vixio. It can't get content(text) of grabbed messages.
Anyway, I couldn't get an working way...

**Comment by iBlitzkriegi** [comment]
ID of has now been changed to Discord Id Of to stop these conflicts from happening. https://github.com/iBlitzkriegi/Vixio/commit/90a58b5cce9ff4bb232858fc9e0ec2817a7062a2
