### ISSUE TITLE
Bugs in many stored message things

### ISSUE THREAD

**Issue by KabanFriends** [iBlitzkriegi/Vixio#170]
Calling same thing multiple time should return same thing but this one is very strange:
![image](https://user-images.githubusercontent.com/45000995/54288986-b6527880-45eb-11e9-9cd2-c18cf21b14c9.png)
Look at this screenshot, the first one returns message ID but the second one doesn't return anything...

for people who cannot see the screenshot:
>!broadcast "%contents of random object out of grabbed messages%"
[23:56:03 INFO]: executing 'broadcast "%contents of random object out of grabbed messages%"'
[23:56:03 INFO]: 555403533910802442
>!broadcast "%contents of random object out of grabbed messages%"
[23:56:04 INFO]: executing 'broadcast "%contents of random object out of grabbed messages%"'
[23:56:04 INFO]: \<none\>

This bug happens in normal script files too, and it's really annoying because I can't make the thing that I want to make due to this glitch.
This NEEDS to be fixed!

**Comment by AlexLew95** [comment]
```vb
set {_grabbed::*} to grabbed messages
broadcast content of random element of {_grabbed::*}
``` try that

**Comment by KabanFriends** [comment]
but why does it return different things when I call that thing twice?

**Comment by KabanFriends** [comment]
and that code still returns nothing

**Comment by iBlitzkriegi** [comment]
His code, as the code says, broadcasts something random from the list? Just save `grabbed messages` to a list variable as `grabbed messages` is overwritten when you retrieve more messages.
