### ISSUE TITLE
Vixio search request

### ISSUE THREAD

**Issue by titustitus98** [iBlitzkriegi/Vixio#171]
**Is your feature request related to a problem? Please describe.**
It is not related to any problems

**Describe the solution you'd like**
The feature I am requesting would be for vixio to search spotify as well as youtube and soundcloud

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by GamingGeek** [comment]
Lavaplayer doesn't support Spotify and adding something like that might be against Spotify's ToS so 99% chance it's not gonna happen

**Comment by titustitus98** [comment]
ok
