### ISSUE TITLE
Used invite expression.

### ISSUE THREAD

**Issue by gp-Airee** [iBlitzkriegi/Vixio#172]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd really like to have an expression for the invite a user joined with. This can work in the guid join event to allow actions to be run when a user uses a specific invite.

**Describe alternatives you've considered**
I give users a separate code to enter when they've been invited to sync with the server but eeh, that's not great.

**Additional context**
NA.

**Comment by GamingGeek** [comment]
Discord doesn't give that info. Only way is by using dumb methods so it won't be added

**Comment by Fiiily** [comment]
> Discord doesn't give that info. Only way is by using dumb methods so it won't be added

How do bots like InviteManager work?
![](https://i.imgur.com/7bwNI6x.png)

**Comment by GamingGeek** [comment]
> How do bots like InviteManager work?
> ![](https://camo.githubusercontent.com/8c28b79716817f1cde2140000b69e46a9b468f25/68747470733a2f2f692e696d6775722e636f6d2f3762774e4936782e706e67)


> 
> > Only way is by using dumb methods
> 
if you want it so badly, use invitemanager

**Comment by Fiiily** [comment]
> > How do bots like InviteManager work?
> > ![](https://camo.githubusercontent.com/8c28b79716817f1cde2140000b69e46a9b468f25/68747470733a2f2f692e696d6775722e636f6d2f3762774e4936782e706e67)
> 
> > > Only way is by using dumb methods
> 
> if you want it so badly, use invitemanager

I want to automatically run actions when people are invited (i.e. minecraft sync.)
If these methods are so "dumb," how can a bot possibly function doing these "dumb methods" on almost 100k servers?

**Comment by GamingGeek** [comment]
> If these methods are so "dumb," how can a bot possibly function doing these "dumb methods" on almost 100k servers?

because they don't use a minecraft server to host their bot and probably have a database running on a vps that can operate on a large scale. It would be dumb to try and do it on a minecraft server **especially** if you are also going to have people playing on it alongside running the bot

**Comment by Fiiily** [comment]
> > If these methods are so "dumb," how can a bot possibly function doing these "dumb methods" on almost 100k servers?
> 
> because they don't use a minecraft server to host their bot and probably have a database running on a vps that can operate on a large scale. It would be dumb to try and do it on a minecraft server **especially** if you are also going to have people playing on it alongside running the bot

Could you at least explain what the method is, why it's bad, and why you can definitively state that Vixio will not offer it?

**Comment by GamingGeek** [comment]
> 
> 
> > > If these methods are so "dumb," how can a bot possibly function doing these "dumb methods" on almost 100k servers?
> > 
> > 
> > because they don't use a minecraft server to host their bot and probably have a database running on a vps that can operate on a large scale. It would be dumb to try and do it on a minecraft server **especially** if you are also going to have people playing on it alongside running the bot
> 
> Could you at least explain what the method is, why it's bad, and why you can definitively state that Vixio will not offer it?

It's not bad when you have a vps and a database to run the bot and a database capable of storing all this info. 
If you really want to do it, you would need to use skript-mirror to access JDA methods to get the invites of a guild, check the usage count against what is already stored in the database and if one has gone up, then you need to check who owns the invite and then do whatever (send a message saying the person joined using the invite, invite use count (and tracking when people leave and deducting a use from the user) etc.), not to mention you would need to do all this inside the `on member join guild`. 

Blitz isn't gonna add all of this to vixio as he would need to add a method of storing invite uses.

**Comment by Pikachu920** [comment]
@GamingGeek https://github.com/discordapp/discord-api-docs/issues/448

Discord plans to add this, so nothing wrong with this issue sticking around here till then

**Comment by Fiiily** [comment]
Don't think Discord will be adding it in the immediate future. How difficult on resources could it be to cache all the invites, listen for Discord joins, immediately save the caches state and check which invite code was used based on number of uses.
Storing basic data like that uses nowhere as much storage as you seem to make it out to use. A file of 1500 lines of 8 char. random generated strings is under 15KB Adding invite numbers to it wouldn't cost much. You don't need an amazing database server or anything to store this kind of data. This kind of data could EASILY be stored in RAM on a server of basically any scale. If it's too much somehow, a configuration toggle would be great. Doesn't even need to default to enabled.

**Comment by Syst3ms** [comment]
The question here is not whether Discord should add it or not, it's whether it should be added in here if Discord adds it. The answer is yes.

**Comment by GamingGeek** [comment]
> The question here is not whether Discord should add it or not
ok? we all know that. that was *never* the question here

**Comment by Syst3ms** [comment]
> ok? we all know that. that was never the question here
I kinda missed @Fiiily's point, actually

**Comment by Fiiily** [comment]
> The question here is not whether Discord should add it or not, it's whether it should be added in here if Discord adds it. The answer is yes.
I'm saying that it wouldn't be intensive to implement that on the end of Vixio.

**Comment by GamingGeek** [comment]
@Fiiily If it gets added officially to discord, I see no reason for it not to be added but any weird methods like I previously explained wouldn't get added

**Comment by iBlitzkriegi** [comment]
This still has yet to be implemented by Discord. If it's ever added feel free to re-open this issue.
