### ISSUE TITLE
Song Lyrics

### ISSUE THREAD

**Issue by titustitus98** [iBlitzkriegi/Vixio#173]
**Is your feature request related to a problem? Please describe.**
No it's not

**Describe the solution you'd like**
So I have no Idea if this already is a feature but it would be cool if you could make your bot display the lyrics of a given song, like rythm does

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by GamingGeek** [comment]
that's not vixios job. you have to make that yourself

**Comment by iBlitzkriegi** [comment]
Would be on the user's side, would take a lot of work if at all even possible.

**Comment by GamingGeek** [comment]
> would take a lot of work if at all even possible.

it's actually quite simple. https://api.ksoft.si/ has a lyrics endpoint that's quite easy to use with reqn and skript-json

**Comment by iBlitzkriegi** [comment]
Quite hard for vixio, not for the user. I'd have to do a lot of work to get it working and itd be unreliable because only I could make modifications if the api changed.
