### ISSUE TITLE
Strange Error Spamming Console

### ISSUE THREAD

**Issue by Moderocky** [iBlitzkriegi/Vixio#174]
**Describe the bug**
A strange error is spamming my console. Roughly every ten seconds, though not a regular pattern.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
This is the error:
https://hastebin.com/ulepejadoj.md

**Additional context**
It might have something to do with shopkeepers? That plugin is mentioned in the error.

**Comment by iBlitzkriegi** [comment]
Without code or context or anything theres nothing I can really do with this.

**Comment by Moderocky** [comment]
There is no code. I had simply installed Vixio.

I have now updated to Skript 2.3.6 and paper-spigot 1.12.2, the error is identical.

There is really no further context that I can give, the error just occurs periodically.
It appears to occur more frequently when there are users online, presumably because very little is actually happening when nobody is on.

**Comment by Moderocky** [comment]
The error does not appear to occur on a server that is running only Skript and Vixio, leading me to believe it might be another plugin conflicting.

**Comment by iBlitzkriegi** [comment]
Hastebin link is dead and as you said it's probably not coming from Vixio then.
