### ISSUE TITLE
why is the size of the plugin so large?

### ISSUE THREAD

**Issue by MrScopes** [iBlitzkriegi/Vixio#175]
title

**Comment by HardstylesDev** [comment]
It has the JDA library added in iirc, that's why it's so big

**Comment by Pikachu920** [comment]
more megabytes = more megagood

**Comment by MrScopes** [comment]
> more megabytes = more megagood

MMMMMM

**Comment by iBlitzkriegi** [comment]
Vixio shades in a entire Emoji Library, a entire Discord library and an entire Audio library. We threw around the idea of downloading the dependencies on runtime but came to the conclusion that it wasn't going to be stable enough. Instability vs just downloading a larger plugin was an obvious choice.
