### ISSUE TITLE
Discord rich presence

### ISSUE THREAD

**Issue by titustitus98** [iBlitzkriegi/Vixio#176]
**Is your feature request related to a problem? Please describe.**
no my feature is not related to any problems

**Describe the solution you'd like**
hi, I was wondering , I have noticed that in the discord developer portal there's a thing called rich presence which allows you to make your game or what ever you are making show up as what you are playing, but is there anyway to use that with vixio

**Describe alternatives you've considered**
none

**Additional context**
nothing

**Comment by SaltyMadrid** [comment]
Not possible for bots.

**Comment by iBlitzkriegi** [comment]
As said, bot's may not use rich presence.
