### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by killergotrekt** [iBlitzkriegi/Vixio#177]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have the bot set someone's nick for a server & give member a role. 

**Describe alternatives you've considered**
no

**Additional context**

**Comment by iBlitzkriegi** [comment]
This is already possible with `set the discord nickname of event-member to "new nickname" with event-bot` (Remember bot's cannot set the nickname of the discord's owner)
