### ISSUE TITLE
Fixed offline player parsing breaking in Vixio

### ISSUE THREAD

**Issue by blizma** [iBlitzkriegi/Vixio#179]
**Is your feature request related to a problem? Please describe.**
I’m always frustrated when using Vixio as it breaks my Scatter lol

**Describe the solution you'd like**
Not sure why Vixio breaks offline player parsing but can it not.

**Describe alternatives you've considered**
not making it break

**Additional context**
none atm

**Comment by iBlitzkriegi** [comment]
It doesn't break offline-player parsing, there is no proof of this and I can't even really gather what you even mean.. 
```
command /test <offline player>:
	trigger:
		broadcast "%arg-1's uuid%"
```
Works as intended, as well as 
```
discord command test <offline player>:
	trigger:
		broadcast "%arg-1's uuid%"
```
.. Also not sure why you created a feature request for a bug..?
