### ISSUE TITLE
Adding Nitro Server Boost Event and Condition

### ISSUE THREAD

**Issue by brjedi** [iBlitzkriegi/Vixio#181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to suggest two things added if possible:
1 - An event that fires whenever a user Nitro Boosts your server
2 - A condition that checks if a certain user has Nitro Boosted your server

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GamingGeek** [comment]
The JDA version Vixio uses doesn't have any features for premium guilds, so that will need to be updated first. Also, there's no event for when someone boosts a server in JDA so unless that gets aded, it won't be in Vixio

**Comment by brjedi** [comment]
Oh, yeah, I suppose it's a little difficult to add if there isn't an API for it. Thanks for the response!

**Comment by iGalaxyYT** [comment]
Wouldn't it be possible to just check if the user has the "Nitro Booster" role?

**Comment by awaffle1** [comment]
> Wouldn't it be possible to just check if the user has the "Nitro Booster" role?

This issue is closed. But it is a good tip lol

**Comment by Evanneuh** [comment]
This feature request should be reopened as JDA4 include this feature
