### ISSUE TITLE
Undetected space in a voice channel.

### ISSUE THREAD

**Issue by NouzDev** [iBlitzkriegi/Vixio#183]
No need to send a screenshot, when we create a voice channel with our bot and try to call it "My bot" the space will not be done and will be replaced by - as if it were a text channel.

Tested with Vixio version 2.0.1

**Comment by iBlitzkriegi** [comment]
Works as intended, cannot reproduce this issue on 2.0.1. 
```
discord command create:
	trigger:
		create voice channel: 
			set the name of the channel to "hey there"
			create the channel in event-guild
```
![image](https://user-images.githubusercontent.com/17624546/60379565-2a7e2400-9a03-11e9-9841-8cb2fe779b11.png)
