### ISSUE TITLE
Not sending messages when in a function

### ISSUE THREAD

**Issue by PARA60N** [iBlitzkriegi/Vixio#185]
**Describe the bug**
When I try to use the send message in a function it simply doesn't send or acts like the var isn't set.

**To Reproduce**
```vbs
function TestVixioBug(t: text):
  broadcast {_t}
  set {_Guild} to "595077680869802004"
  set {_Channel} to "595170519599284235"
  send {_t} to channel with id {_Channel} in guild with id {_Guild} with "DataMine"

command /testbug [<text>]:
  trigger:
    TestVixioBug(arg 1)
```

**Expected behavior**
When I send the message it should send the message in the function

**Comment by iBlitzkriegi** [comment]
I'm not able to reproduce this, 
```
function TestVixioBug(t: text):
	broadcast {_t}
	send {_t} to channel with id "381938023627096064" with "Jewel"

command /testbug [<text>]:
	trigger:
		TestVixioBug(arg 1)
```
Works as intended, https://gyazo.com/c6dd92bd0e990fa29195b4a78ce792d4

**Comment by Govindass** [comment]
it's a bug of 2.3.7 Skript, you can't use local variables in delayed stuff such as sending messages to discord, you need to set text to global variables here
