### ISSUE TITLE
[Suggestion] Attachments

### ISSUE THREAD

**Issue by Tai1er** [iBlitzkriegi/Vixio#187]
**Is your feature request related to a problem? Please describe.**
Yes. There is no expressions for message's attachements

**Describe the solution you'd like**
A support for message's attachments to get informations about the attachements of a message like the name and the url.

**Describe alternatives you've considered**
Images are only supported in embed.

**Additional context**
I have linked my Minecraft chat with a Discord channel and I just want to send the url of an image in my Minecraft chat when someone post it in the Discord channel.

(Have a nice day :D)

**Comment by iBlitzkriegi** [comment]
This has been added; https://github.com/iBlitzkriegi/Vixio/compare/5dd828f506c4...dcb859da5bd1. With the ability to get the name, url, height, width and id of an attachment.
