### ISSUE TITLE
[BUG Report] LavaPlayer System

### ISSUE THREAD

**Issue by XxRogerxX-SPMC** [iBlitzkriegi/Vixio#190]
## [Bug Report] Lavaplayer system

**Description**
The error is in the version 2.0.0 and 2.0.1.
The problem is only happening with YouTube and isn't with SoundCloud

**Code**
The problem is happening with the Example in the channel of examples of the Vixio's discord

**How can I get the error?**
With:
`play url of {_results::1}`

With:
`play {_results::1}`
the error does not come out

[Click here to view the error](https://pastebin.com/raw/fP2vTv26)

**Comment by wohahobg** [comment]
Yes some songs cannot be playing for somereason.. They have to update the youtube API some songs are okey but some are not..

**Comment by XxRogerxX-SPMC** [comment]
> Yes some songs cannot be playing for somereason.. They have to update the youtube API some songs are okey but some are not..

no song from youtube works for me and that is what confuses me

**Comment by wohahobg** [comment]
How look at your erros ``[02:30:15 - ERROR] Error in loading item https://www.youtube.com/watch?v=GWbgMDDzltA`` song from youtube does not load..

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> How look at your erros `[02:30:15 - ERROR] Error in loading item https://www.youtube.com/watch?v=GWbgMDDzltA` song from youtube does not load..

yes. for me this say that in all songs

**Comment by iBlitzkriegi** [comment]
Fixed, released in vixio discord #general
