### ISSUE TITLE
Bot Execute

### ISSUE THREAD

**Issue by XxRogerxX-SPMC** [iBlitzkriegi/Vixio#196]
## Expression:
`make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`

## For what!?
This is for a bot to execute a command from another bot that is also handled by vixio, it is something that I see useful and according to me if it can be done.

## Event:
`bot execute (discord command|discord cmd) %discord cmd%`

With strings:
`event-dcmd | event-discordcmd`
`event-bot`
`event-channel`

**Comment by KAMIL0024** [comment]
bot cannot execute commands

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> bot cannot execute commands

You can do it, by having the vixio bot that has that command, when detecting a message received by the other bot, verify if the message is a command created by vixio.
I could verify it in the form of a message.

**Comment by XxRogerxX-SPMC** [comment]
That is why I specified from the beginning that the command to be executed is of vixio, this would help to make a unification of 2 servers for a specific action, which is my case I am doing that when executing a command unites the mc account and the one of Discord in 2 servers making the user only in one, and those servers are not united so I do it via Discord.

**Comment by KAMIL0024** [comment]
Completely pointless. Give an example of using this.

**Comment by XxRogerxX-SPMC** [comment]
It would not be useless, it would help a lot in many aspects is a matter of creativity of each person, it is optional if you want to add it on your own, it is your decision but if you do not want you will not be forced

**Comment by XxRogerxX-SPMC** [comment]
It will take me a few minutes but I will

**Comment by KAMIL0024** [comment]
I recommend using the function.

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> I recommend using the function.

It doesn't work that way.
I am having bot 1 execute a bot 2 command
The 2 are on different servers, so I can't do that.
The 2 are not connected via Bungeecord or any type of link with what my unification is done by a private discord in which the user to join his minecraft account with that of discord on one of the 2 servers, a command is sent with the expression that I have put which is sent to the other bot that is on the other server, and if that other bot has the command to execute it and so the accounts are unified, you can use the example of the example channel of the discord of vixio , there you will find the unification what would be missing is that I send the command bot 1 and that bot 2 receives it

**Comment by KAMIL0024** [comment]
1. How would the bot know that the other bot is connected to Vixio?
2. How would the bot know the prefix of 2 bot?
3. Vixio has the dependency `if event.getUser(). IsBot() return;`
4. Your syntax has errors.

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
>     1. How would the bot know that the other bot is connected to Vixio?
> 
>     2. How would the bot know the prefix of 2 bot?
> 
>     3. Vixio has the dependency `if event.getUser(). IsBot() return;`
> 
>     4. Your syntax has errors.
I just told you that for that I would have to increase a verifier or it would be a new form as an expression, `bot discord command example [<text>] [<text>]`
or I would simply add a verifier to the current expression and now, do not complicate yourself looking for errors, you can do it now, but for that you have to use a lot of code.

**Comment by fdsfd-skripts** [comment]
Here's 1 and 2 answered for you.
1. Take skript's reload and make kinda a replica but it scans for Vixio stuff.
2. If I were to use this effect (a guess on what it will be classified as), I would use it as `make event-bot run command "command" with prefix "prefix"`

**Comment by XxRogerxX-SPMC** [comment]
It would be literally the same as what I am suggesting is not different.

**Comment by ilsubyeega** [comment]
blitz will be work harder rip

**Comment by ilsubyeega** [comment]
and what will be returning in this *expression*?
`make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> blitz will be work harder rip
> but it looks useless just using mysql or redis etc

I just told you that I don't want to have servers attached, I don't have a mysql right now and it wouldn't be so good to use it as a method for that.

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> and what will be returning in this _expression_?
> `make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`

The same name says what he will do.

**Comment by ilsubyeega** [comment]
> 
> 
> > and what will be returning in this _expression_?
> > `make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`
> 
> The same name says what he will do.

i said expressions not effects

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> > > and what will be returning in this _expression_?
> > > `make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`
> > 
> > 
> > The same name says what he will do.
> 
> i said expressions not effects

I know that it is a strong job, but for those who are just going to start with Vixio, but have a requirement almost equal to what I have at the moment.

**Comment by XxRogerxX-SPMC** [comment]
> 
> 
> > > and what will be returning in this _expression_?
> > > `make (with %bot%|%bot%) execute (discord command|discord cmd) %discord command% [of bot %bot%]`
> > 
> > 
> > The same name says what he will do.
> 
> i said expressions not effects

I know, but for that he simply would not increase Effects for this, I understand that that is not something necessary in itself in this.

**Comment by iBlitzkriegi** [comment]
You do understand that bot's cannot dm eachother correct? So why not have bot 1 send a message in a channel with all the content bot 2 will need to parse. I.e any information about the user and bot 2 will just on `on guild message received` and parse out all the data from the message.

**Comment by XxRogerxX-SPMC** [comment]
Oka,Thanks xd
