### ISSUE TITLE
Store the effect errors.

### ISSUE THREAD

**Issue by KAMIL0024** [iBlitzkriegi/Vixio#198]
**Is function request a problem? Please describe.**
I am always frustrated when `the last vixio error` is not related to the main thread.

Example:
```
ban arg-1 from event-guild
set {_e::*} to last vixio error
if {_e::*} is set:
    reply with "Oh, %{_e::*}%"
    stop
```
{_e} return `Token is invalid`

**Describe the solution you'd like**
I suggest adding `[and store [the] error[s] in %list variable%]` at the end of syntax.

**Describe alternatives you've considered**
```
play arg-1 and store the error in {_e::*}
if {_e::*}:
    reply with "Error: %{_e::*}%"
    stop
reply with "Add sound to quene!"
```
~sr for bad eng~

**Comment by iBlitzkriegi** [comment]
This would be too much of a task to add to the end of each and every syntax. You would just have to check if the last vixio error has a certain text in it. I.e if "Permission error" is in {_e::*}. I will look into Vixio's errors to see if I can implement adding more information into them to help distinguish an error this way.
