### ISSUE TITLE
1.0.4 To-dos

### ISSUE THREAD

**Issue by itismejoey** [iBlitzkriegi/Vixio#2]
- [ ] Add a way to return Youtube and Google searches in specific channels.
- [ ] Add a way to clearchat in a certain channel with by a certain amount of messages
- [x] Add a way to set roles
- [x] Syntax for values you can get from event-channel
- [x] Syntax to get stuff about the guild a event was fired in.

**Comment by awaffle1** [comment]
n e c r o p o s t i n g

It's funny how I stumbled apon this looking through the issues section- actually, I looked in the Milestones tab and found this. 1.0.4 is a really old version lol

**Comment by ilsubyeega** [comment]
dont bump up
