### ISSUE TITLE
[Bug Report] Reaction System

### ISSUE THREAD

**Issue by XxRogerxX-SPMC** [iBlitzkriegi/Vixio#201]
## Describe the bug
Error in console and Reaction name

## Bug Info
I don't know xD i don't have skript problems that problem is only in the version 2.0.2 and isn't in 2.0.1.

## Code
[Click here](https://pastebin.com/raw/xBWMAKVn)

**Comment by iBlitzkriegi** [comment]
Fixed here; https://github.com/iBlitzkriegi/Vixio/commit/9598b72a0484d3f9efee4df681e2287eae38a53d
