### ISSUE TITLE
Retrieve message bug

### ISSUE THREAD

**Issue by KAMIL0024** [iBlitzkriegi/Vixio#204]
**Describe the bug**
The code stops if id is wrong

**To Reproduce**
```
discord command test [<text>]:
	prefixes: "%{bot::prefix}%", "%mention tag of event-bot% "
	trigger:
		reply with "1"
		retrieve message with id arg-1 from event-channel
		reply with "2"
```
![image](https://user-images.githubusercontent.com/39656013/64907923-60c16a80-d6f9-11e9-91ae-0d6b9e788757.png)

Error in console:
![image](https://user-images.githubusercontent.com/39656013/64907935-9d8d6180-d6f9-11e9-9e4f-d39993fcfae3.png)

**Expected behavior**
Idk, get a message by id

**Comment by Olyno** [comment]
This error means your message doesn't exist.

**Comment by KAMIL0024** [comment]
> This error means your message doesn't exist.

I know, but the problem is that the error stops the code. ("2" is not sent)

**Comment by Olyno** [comment]
> > This error means your message doesn't exist.
> 
> I know, but the problem is that the error stops the code. ("2" is not sent)

It's totally normal. You have an exception, so it's stops your code. Resolve this exception and your work will be fine.

**Comment by iBlitzkriegi** [comment]
Fixed in this commit; https://github.com/iBlitzkriegi/Vixio/commit/bd902308c51ae9710534399ad64817ff3fced2fc . Now replaced with a warning 
![image](https://user-images.githubusercontent.com/17624546/66004899-e6724380-e477-11e9-9d3d-8230e697cfd5.png)
