### ISSUE TITLE
Can't get the event-reaction in Vixio 2.0.2

### ISSUE THREAD

**Issue by Grabsky** [iBlitzkriegi/Vixio#205]
**Describe the bug**
After I updated (from Vixio 2.0.0) to Vixio 2.0.2, I can't detect the event-emote in **on reaction add** event.

**To Reproduce**
1. Add this code and reload script:
```
on reaction add:
	if discord name of event-emote is "one":
		reply with "1"
```
2. Add reaction one to any message in guild.

**Expected behavior**
Bot will reply with string "1".

**Additional context**
Console will be flooded with this error whenever I add emote to a message: https://paste.ubuntu.com/p/9x767RmCQX/

**Comment by iBlitzkriegi** [comment]
This was fixed in https://github.com/iBlitzkriegi/Vixio/commit/9598b72a0484d3f9efee4df681e2287eae38a53d and will be released soon
