### ISSUE TITLE
[Suggestion] Rename Channel

### ISSUE THREAD

**Issue by XxRogerxX-SPMC** [iBlitzkriegi/Vixio#206]
# Sugesttion

Effect: 
`vixio rename (%text-channel%/%voice-channel%) to %string% [with (%bot%/%string%)]`

## Description
Currently, I have tried in many ways to change the name of an existing channel with vixio, this effect would greatly facilitate the renaming of a channel

**Comment by iBlitzkriegi** [comment]
You can already do this by using the set changer on discord name of. You just `set` the `discord name of` the channel to a string.
