### ISSUE TITLE
Vixio, "set ... to the last vixio error"

### ISSUE THREAD

**Issue by KnuffelBeestje** [iBlitzkriegi/Vixio#208]
**Describe the bug**
Vixio doesn't store the error in a variable when vixio isn't mentioning the error in console.
For example:

**DOESN'T WORK**
I tried to set slots from a discord voice channel to 2, it gave me the following error that the bot  didn't have the permissions.
"[22:07:39 ERROR]: [net.dv8tion.jda.core.requests.RestAction] RestAction queue returned failure: [InsufficientPermissionException] Cannot perform action due to a lack of Permission. Missing permission: MANAGE_CHANNEL" 
When this happends, the error isn't set to any variable and "if {_error} is set:" wouldn't work.

**WORKS:**
Trying to kick somebody without permissions gave the following console error:
" [22:13:52 INFO]: [Vixio] Vixio tried to run the action kick user with bot ThunderGuard but was missing the Kick Members permission!" -> (note the [Vixio] in the front)
When this happens, the variable is set with the vixio error; (if {_error} is set) should work now.

**To Reproduce**
Already explained above ^^^^

**Expected behavior**
The error should always be set in a variable.

**Comment by iBlitzkriegi** [comment]
Vixio's only supposed to store its own errors, that means this is actually an issue with that exception not being caught in setting the size of the voice channel.

**Comment by iBlitzkriegi** [comment]
When you make issues make sure you give the code you used to reproduce it.. I tried with 
```
discord command test <voicechannel>:
	trigger:
		set the user limit of arg-1 to 2
```
and it worked as intended; 
![image](https://user-images.githubusercontent.com/17624546/66431980-13c86f80-e9eb-11e9-9c82-1d1a05170092.png)

**Comment by iBlitzkriegi** [comment]
I can't reproduce this, I've tried ever manner of it. Even making everything included variables to see if it was a syntax matching problem but all is working as intended.
