### ISSUE TITLE
removing a role doesn't work

### ISSUE THREAD

**Issue by NeNex-GitHub** [iBlitzkriegi/Vixio#210]
**Describe the bug**
When i try to remove a role to a member, nothing is happening.
i used : remove role with id "id" from roles of user with id "id" in guild with id "id" with "botname"
there is no error but the role isn't removed
this code is working for vixio version 2.0.1
this bug appears in versions after 2.0.1
i use spigot 1.8.8

but adding a role is working in the same command with the same ids
add role with id "id" to roles of user with id "id" in guild with id "id" with "botname"

**Comment by Hiiva** [comment]
Try ”discord id” instead of ”id”.

**Comment by NeNex-GitHub** [comment]
I have an unknown syntax error when I put "discord id"

**Comment by Matocolotoe** [comment]
Can confirm this issue.

**Comment by HardstylesDev** [comment]
Can verify.
