### ISSUE TITLE
Emote request

### ISSUE THREAD

**Issue by Mattyb0i** [iBlitzkriegi/Vixio#211]
Hey.

Right now, i can't use emotes in embeds. I tried :emote:, but it is converting to a text, and i can't  find a solution.

I will hear, if it could be possible to add emote support for embeds, so i can use them in my embeds.

Solution :emote: converts to my emote, i created or a existing emote.

**Comment by iBlitzkriegi** [comment]
I tested this and it works as intended. You have to use the emote expression to reference a emote. I.e %emote ""smile""% would give this: 
![image](https://user-images.githubusercontent.com/17624546/74067983-7c8b1d00-49c8-11ea-97dd-567a447e17ca.png)
