### ISSUE TITLE
sending a dm causes errors for different events

### ISSUE THREAD

**Issue by HardstylesDev** [iBlitzkriegi/Vixio#216]
Sending a DM, seems broken to me sir.

```
discord command dmerror:    
    bots: Blitz
    trigger:
        send "xd" to event-member with event-bot
```
This might not seem to give an error at first, but it makes everything related to the `on message receive seen by XXX` glitch out. Prints about 40 of those messages (depending on the amount of `on guild message receive`  events you have.

https://hastebin.com/ukisulojaj.shell

**Comment by mc1a3** [comment]
I'd guess that'd be because your using a member rather than a user.

**Comment by iBlitzkriegi** [comment]
![image](https://user-images.githubusercontent.com/17624546/68619227-0a726d00-0499-11ea-8392-5a39f212b2ba.png)
as it says
