### ISSUE TITLE
Create a server invitation

### ISSUE THREAD

**Issue by CarloDrift** [iBlitzkriegi/Vixio#219]
Hi,

`create an invite to event-channel with "bot" and store it in {_invite}` This effect works.
`create an invite to channel with id "<ID>" with "bot" and store it in {_invite}` This one doesn't work and sends the following error to the console: https://pastebin.com/wC4KVdhg

Vixio version: v2.0.3
Skript version: 2.4-beta9
Server version: Spigot 1.14.4

**Comment by iBlitzkriegi** [comment]
You logged out of your bot or something of that nature. The bot closed down, it was by chance that error happened

**Comment by CarloDrift** [comment]
> You logged out of your bot or something of that nature. The bot closed down, it was by chance that error happened

The bot is still online after and that makes the same error every time I use this effect!

**Comment by iBlitzkriegi** [comment]
did you try restarting the server

**Comment by CarloDrift** [comment]
It doesn't make the error anymore, but I have something even more strange!
`create an invite to channel with id "643142094768177207" with "bot" and store it in {_invite}` This effect works.
`create an invite to channel with id "%{_channel}%" with "bot" and store it in {_invite}` This one doesn't work. The variable {_channel} is "643142094768177207" but it does not create an invitation!

**Comment by CarloDrift** [comment]
I think he doesn't like variables!
`set {_channel} to "643142094768177207"`
`create an invite to channel with id "%{_channel}%" with "bot" and store it in {_invite}` This doesn't work.

**Comment by iBlitzkriegi** [comment]
Can't reproduce this, check your id's.

**Comment by CarloDrift** [comment]
`discord command invite <text>:`
	`prefixes: +`
	`trigger:`
		`set {_} to channel with id "%arg-1%"`
		`create an invite to {_} with event-bot and store it in {_invite}`
		`reply with "%{_invite}%"`
You can test, it doesn't work!

**Comment by iBlitzkriegi** [comment]
![image](https://user-images.githubusercontent.com/17624546/68552040-b310c600-03e0-11ea-91c2-bdf2a4fcfc1c.png)
Still works fine

**Comment by CarloDrift** [comment]
I just tested the same code, it does not work on my side... No console error.

**Comment by CarloDrift** [comment]
What could be the cause?

**Comment by CarloDrift** [comment]
I don't understand how it can work with you and not with me...

**Comment by CarloDrift** [comment]
Solved by switching from a temporary variable to a classic variable. The mysteries of Skript...
