### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ssaa1122** [iBlitzkriegi/Vixio#228]
**Describe the bug**
When i try to run the ban, kick commands it respond me with this error but when i try the ping command it works fine

**Information**
Skript version: 2.4
Vixio version: 2.0.3
Minecraft Version: 1.14.4
Server software name and version: Linux amd64 4.15.0-60-generic

**Expected behavior**
I expected it to ban the member but it shows the error

**Screenshots**
![image](https://user-images.githubusercontent.com/48889497/71261537-7646c180-22f2-11ea-8b67-e0187fbc876b.png)

**Comment by XxRogerxX-SPMC** [comment]
## Check:

- Check bot permissions

## Code:

- Verify your code.

## Logs

- Send your error.
