### ISSUE TITLE
User channel permission bug

### ISSUE THREAD

**Issue by CarloDrift** [iBlitzkriegi/Vixio#230]
**Describe the bug**
It's impossible to grant permissions to a user in a channel.

**To Reproduce**
```
on reaction add:
	deny event-user the permission message read in event-channel
```
Error: event-types.user is neither a types.role nor a types.member

**Information**
Skript version: 2.4
Vixio version: 2.0.3
Minecraft Version: 1.14.4
Server software name and version: Spigot 1.14.4-R0.1-SNAPSHOT

**Comment by HardstylesDev** [comment]
Works fine, just because you're not using the right syntax doesn't mean it's an error 😊

event-user -> event-member
