### ISSUE TITLE
Problem adding a role

### ISSUE THREAD

**Issue by CarloDrift** [iBlitzkriegi/Vixio#231]
**Describe the bug**
Adding a role works well. However, sometimes it doesn't work, and this sends an error to the console.
```
[Skript] method RoleActionImpl#queue called without arguments threw a IllegalStateException: The Requester has been shutdown! No new requests can be requested!
```

**To Reproduce**
I haven't been able to find the source of the problem.

**Information**
Skript version: 2.4
Vixio version: 2.0.3
Minecraft Version: 1.14.4
Server software name and version: Spigot 1.14.4-R0.1-SNAPSHOT

**Additional context**
```
add {_role} to roles of event-user in event-guild with event-bot	
```

**Comment by iBlitzkriegi** [comment]
This is because you had used the shutdown effect or your bot had shutdown so it couldn't add roles.
