### ISSUE TITLE
Severe error bug report

### ISSUE THREAD

**Issue by HerozOfficial** [iBlitzkriegi/Vixio#234]
**Describe the bug**
Severe error when loading skript, But the skript itself has no errors.
**To Reproduce**
Loading the skript

**Information**
Skript version: 2.3.7
Vixio version: 2.0.2
Minecraft Version:  1.12.2
Server software name and version:
Spigot 1.12.2 OS: Linux amd64 4.9.177-xxxx-std-ipv6-64
**Expected behavior**
Things aren't working because of severe error

**Screenshots**
None, Just severe error

**Additional context**
ERROR: https://pastebin.com/Pw5qvRrd
No, Just randomly happens

**Comment by ilsubyeega** [comment]
Can you give us file named AYC.sk? those error happens when reloading AYC.sk

**Comment by HerozOfficial** [comment]
> Can you give us file named AYC.sk? those error happens when reloading AYC.sk

Well yes, But then i'd be giving you my entire bot..?

**Comment by Olyno** [comment]
> Are you vixio staff or something?

Who cares of that? You say that to reproduce your issue we must "Loading the skript", but where is your script? We need it to load it lol

**Comment by HerozOfficial** [comment]
> > Are you vixio staff or something?
> 
> Who cares of that? You say that to reproduce your issue we must "Loading the skript", but where is your script? We need it to load it lol

Okay, Code: https://pastebin.com/V0A8zrHm

**Comment by HardstylesDev** [comment]
Replace `id of` with `discord id of ` because that's outdated

**Comment by HerozOfficial** [comment]
> Replace `id of` with `discord id of ` because that's outdated

ALL of them are "discord id of" though??

**Comment by iBlitzkriegi** [comment]
Replace the `
    prefixes: "%{%scripts%::%discord id of event-guild%::prefix}%"` with a normal standard prefix like ! and see if it begins working

**Comment by HerozOfficial** [comment]
> Replace the ` prefixes: "%{%scripts%::%discord id of event-guild%::prefix}%"` with a normal standard prefix like ! and see if it begins working. Could also technically remove the whole prefixes line for testing purposes ig.

Fixed, Thank you, This was not a problem before 2.0 so i didnt know why
