### ISSUE TITLE
On guild join [broken]

### ISSUE THREAD

**Issue by KnuffelBeestje** [iBlitzkriegi/Vixio#235]
**Describe the bug**
"On guild join:" is not a valid event.

**To Reproduce**
Add "on guild join:" or "on guild join seen by "botname:"" to your skript.
Reload and see the following error: "[04:39:04 ERROR]: [Skript] can't understand this event: 'on guild join'"

**Information**
Skript version: v2.4.1
Vixio version: v2.0.4
Minecraft Version: v1.12.2
Server software name and version: Paper 1.12.2

**Expected behavior**
The event should be working and fired.

**Additional context**

**Comment by 1A3Dev** [comment]
Try `on member join guild:` and see if it works then
