### ISSUE TITLE
Adding reactions in a direct message isn't working.

### ISSUE THREAD

**Issue by Mattyb0i** [iBlitzkriegi/Vixio#237]
**Describe the bug**
When I click this reaction (Example) https://gyazo.com/a1252009fc6dc334aee9aed73967375d, then my bot sent a private message to me, but without any reactions added, because direct messages isn't a text channel.

I also tried in a guild without any errors.

**To Reproduce**
1. Use this code https://pastebin.com/zWRg5FvK
2. Reload your script
3. Click this reaction: https://gyazo.com/a1252009fc6dc334aee9aed73967375d
4. Now I got the private message, but I also get the error in my console. - 

**Information**
Skript version: 2.2 dev37c
Vixio version: 2.0.4
Minecraft Version: 1.8.8
Server software name and version:
PaperSpigot-8b18730

**Expected behavior**
I want the bot to add two reactions. x and white_check_mark, but when i try to use it in a direct message, then Skript prints out a error in my console -

Console error: https://gyazo.com/13ed63cd9c55ef8d96b9a20d5bb01587

**Comment by iBlitzkriegi** [comment]
Fixed here: https://github.com/iBlitzkriegi/Vixio/commit/53d024b7b673f30960765a2b18b704067e5a63ec
