### ISSUE TITLE
can't change name of channel 

### ISSUE THREAD

**Issue by jeuxdictator** [iBlitzkriegi/Vixio#239]
**Describe the bug**
Skript doesn't recognize "set name of voice channel with id arg-1 to arg-2 with event-bot" (copied from the example)

**To Reproduce**
1.copy paste the example (https://olyno.github.io/Vixio/documentation/#voice_channel_with_id)
2.reload the skript and see that it can't recognize the expression

**Information**
Skript version: 2.4.1
Vixio version: 2.0.4
Minecraft Version: 1.14.4
Server software name and version: Paper 213

**Expected behavior**
I expected the expression to be recognized but it doesn't

**Screenshots**
http://prntscr.com/qpi7ly

**Comment by Olyno** [comment]
The reason is really simple: the documentation is not up to date yet.

**Comment by jeuxdictator** [comment]
Oh, then I'm terribly sorry for reporting such a minor thing, but then, can you tell me how can I rename a channel please ?

**Comment by Olyno** [comment]
> Oh, then I'm terribly sorry for reporting such a minor thing, but then, can you tell me how can I rename a channel please ?

I did an update of the website. You can see new syntaxes on it via ``vixio.tk`` or ``olyno.github.io/VixioSite`` urls.

**Comment by jeuxdictator** [comment]
Well, it seems that the example https://olyno.github.io/VixioSite/#voice_channel_with_id is yet broken because it tells me the same thing (with the version on your site : http://prntscr.com/qq840a)

**Comment by jeuxdictator** [comment]
My bad I used the wrong thing I tried to used a channelbuilder from the whole time, I'm so sorry for taking time of your life for such a stupid thing, many thanks

(for those who who wanted to know wich thing to use, I use https://olyno.github.io/VixioSite/#name_of and it work perfectly fine)
