### ISSUE TITLE
Ghost error.

### ISSUE THREAD

**Issue by HerozOfficial** [iBlitzkriegi/Vixio#241]
**Describe the bug**
Using the code in my bot gives me 6 "ghost errors", Console says "6 errors" but doesn't actually show any errors or the lines the errors are on, Please fix.

**To Reproduce**
Use the code in this link: https://pastebin.com/vExryHKA

**Information**
Skript version: 2.3.7
Vixio version: 2.0.4
Minecraft Version: 1.12.2
Server software name and version: Spigot 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by HardstylesDev** [comment]
Fixed
