### ISSUE TITLE
Purge all messages in a channel

### ISSUE THREAD

**Issue by RasmusHJV2** [iBlitzkriegi/Vixio#245]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to delete all the messages in a channel manually.

**Describe the solution you'd like**
I want to make so I can purge all messages in a channel, with a phrase like purge all messages in guild with id "----" or something like that.

**Describe alternatives you've considered**
I think this is the easiest way to make it.

**Additional context**

**Comment by KAMIL0024** [comment]
Its not possible

**Comment by HardstylesDev** [comment]
Why not?

**Comment by Pikachu920** [comment]
because it would kill your rate limits. discord only let's you delete 100 messages at a time and you can only do that once every 3 seconds or something. It would take way too long to purge an entire decently sized guild or channel

**Comment by ilsubyeega** [comment]
[Accroading to docs](https://discordapp.com/developers/docs/resources/channel#bulk-delete-messages), will not possible. bulk delete limits 100, but like Pikachu920 says it will get rate limited if you actually doing it. and bulk delete wont delete messages older than 2 weeks. so just delete channel and create channel can be solution idk

**Comment by HardstylesDev** [comment]
I'd suggest just cloning the channel then

**Comment by iBlitzkriegi** [comment]
Just clone the channel, delete the old one and place the new one in the same position.
