### ISSUE TITLE
Error on playing music (lavaplayer issue)

### ISSUE THREAD

**Issue by Shurelia** [iBlitzkriegi/Vixio#249]
**Describe the bug**
Can't play music, Lavaplayer throws error

**To Reproduce**
1. play a music command on discord

**Information**
Skript version: 2.5-alpha3
Vixio version: 2.0.4 
Minecraft Version: tried both 1.12.2 and 1.15.2
Server software name and version: 
1.12: Mohist-1.12.2-b2916a4 
1.15: Paper-1.15.2-b208

**Expected behavior**
playing music?

**Screenshots**
error log: https://gist.github.com/Shurelia/a405b4442e7fe2234cd4884c53c2ad11

**Additional context**
nothing i guess

**Comment by XxRogerxX-SPMC** [comment]
`Download latest version of Vixio (2.0.5)`

**Comment by Shurelia** [comment]
> `Download latest version of Vixio (2.0.5)`

where? searched the entire git and didnt found it, even on spigot

**Comment by Shurelia** [comment]
found it, and it worked, tysm^^
