### ISSUE TITLE
Check roles does not work

### ISSUE THREAD

**Issue by Gustenberg** [iBlitzkriegi/Vixio#253]
```
discord command !role <member> <string>:
    trigger:
        if arg-1 has role named arg-2:
            reply with "%arg-1% does have a role named %arg-2%"
            stop
        reply with "%arg-1% does not have a role named %arg-2%"
```

It doesn't work properly
It says that the person does not have the role even if he / she has

**Comment by KAMIL0024** [comment]
https://cdn.discordapp.com/attachments/683291621634211870/713478453101330473/unknown.png

**Comment by Gustenberg** [comment]
@KAMIL0024 it doses not work https://i.imgur.com/D4ILkzI.png

**Comment by KAMIL0024** [comment]
```
set {_user} to user with id "123456789" IN {_GUILD}
```

**Comment by Gustenberg** [comment]
> set {_user} to user with id "123456789" IN {_GUILD}

What?

**Comment by Gustenberg** [comment]
@KAMIL0024

**Comment by Olyno** [comment]
If you are using the latest Vixio version, please check the docs because you are not using right syntaxes: https://olyno.github.io/VixioSite/

**Comment by will2022** [comment]
> If you are using the latest Vixio version, please check the docs because you are not using right syntaxes: https://olyno.github.io/VixioSite/

He is actually using the example from the docs. https://olyno.github.io/VixioSite/#member_has_role

**Comment by Olyno** [comment]
> > If you are using the latest Vixio version, please check the docs because you are not using right syntaxes: [olyno.github.io/VixioSite](https://olyno.github.io/VixioSite/)
> 
> He is actually using the example from the docs. [olyno.github.io/VixioSite/#member_has_role](https://olyno.github.io/VixioSite/#member_has_role)

Literally not. Syntax is asking a ``role`` type, not a ``string`` type. Of course it will not work.
Please refer to the doc (https://olyno.github.io/VixioSite/#role_named) and Skript basics

**Comment by will2022** [comment]
![image](https://user-images.githubusercontent.com/12783306/83197650-158fa080-a13e-11ea-8808-0f2c0f2ce765.png)
That's a string type?

**Comment by Olyno** [comment]
Yes but if the current one doesn't work, maybe should it be smarter to try another syntax.

**Comment by iBlitzkriegi** [comment]
I can't reproduce this I use the syntax constantly.
