### ISSUE TITLE
[ISSUE] send message to user

### ISSUE THREAD

**Issue by PuchiGFX** [iBlitzkriegi/Vixio#255]
I can't send private messages to users if i use their id.
My code:
https://hastebin.com/magovanera.bash

Screenshots:
In discord server:
![image](https://user-images.githubusercontent.com/64415723/84995299-24211480-b14c-11ea-8164-dc6114007bda.png)
In pm:
![image](https://user-images.githubusercontent.com/64415723/84995374-3bf89880-b14c-11ea-8b33-4dc1fa198124.png)

Skript version: 2.4.1
Vixio version: 2.0.4
Minecraft Version: 1.15.2
Server software name and version: git-Paper-172 (1.15.2)

**Comment by PuchiGFX** [comment]
I found something interesting:
My current code:
https://hastebin.com/nokoxotogu.pl

Screenshots:
In discord server:
![image](https://user-images.githubusercontent.com/64415723/85340978-75802980-b4e7-11ea-89f9-0b93093f2389.png)
In private message:
![image](https://user-images.githubusercontent.com/64415723/85341016-86309f80-b4e7-11ea-8ff5-8c823653fb14.png)

**Comment by PuchiGFX** [comment]
I fixed it using normal variables (I don't know why i didn't test that before).
By the way, i think that the bot can't use temporary variables for private messages is a bug.

**Comment by iBlitzkriegi** [comment]
That is just a skript issue. Was intentionally made that way at some point
