### ISSUE TITLE
Vixio break 'is|isn't online|offline' condition of Skript

### ISSUE THREAD

**Issue by AzonFR** [iBlitzkriegi/Vixio#266]
Since i've installed Vixio on my server, in my scripts, all conditions with 'is online' or 'is offline' or 'isn't offline'.. are broken, they return anything, if i'm online, the 'is online' condition is false, same for is offline ...

Skript version: latest (2.5-alpha6)
Vixio version: latest (2.0.4)
Minecraft Version: 1.8.8
Server software name and version: Ubuntu 18.04

**Comment by AzonFR** [comment]
For example, this code will work fine without Vixio:
`command /ttp <text>:
  trigger:
    if arg parsed as player is online:
      teleport(player, arg parsed as player)
    else:
      send "&cThis player is offline."
    set {_p} to arg parsed as player
    if {_p} is online:
      teleport(player, arg parsed as player)
    else:
      send "&cThis player is offline."`
But with Vixio, the condition `arg parsed as player is online` works well, but the other with local variable will not, so i think Vixio break the `is online` condition when using local variables

**Comment by AzonFR** [comment]
The issue is still present with latest update...

**Comment by iBlitzkriegi** [comment]
First off you not using the format makes me want to close without reading it. Nonetheless I don't understand what the issue even is, Vixio doesn't control local variables?
