### ISSUE TITLE
 send messages/embeds isn't working

### ISSUE THREAD

**Issue by killergotrekt** [iBlitzkriegi/Vixio#268]
**Describe the bug**
function to send messages/embeds isn't working

**To Reproduce**
1. create a file
2. paste this code in
```
discord command /eval <text>:
    trigger:
        if arg-1 = "error-msg":
            sendErrorMSG(event-channel)
            reply with "attempting to send error-msg for dev purposes"

function sendErrorMSG(c: channel):
    send "Oops! An error has occured on our end." to {_c} with "mybot"
```
3. reload the file

**Information**
Skript version: 2.5-alpha3
Vixio version: 2.0.6
Minecraft Version: **Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
Server software name and version: Windows 10 Pro Version 1903

**Expected behavior**
The *send "Oops! An error has occured on our end." to {_c} with "mybot"* should be executed to the same channel

**Comment by itzoreomc** [comment]
What about login?

**Comment by itzoreomc** [comment]
discord command /eval <text>:
    trigger:
        if arg-1 = "error-msg":
            sendErrorMSG(event-channel)
            reply with "attempting to send error-msg for dev purposes"

function sendErrorMSG(c: channel):
    send "Oops! An error has occured on our end." to {_c} with "mybot"
do nothing because you dont login with you bot token.

**Comment by iBlitzkriegi** [comment]
This works perfectly fine for me with this code 
```
function test(c: channel):
	send "test" to {_c} with "{@bot}"
	
discord command test:
	trigger:
		test(event-channel)
```
![image](https://user-images.githubusercontent.com/17624546/90320018-6035e300-df0b-11ea-9e9e-29bff9971630.png)

Could it be something with your skript version? Could try changing versions around.

**Comment by killergotrekt** [comment]
Which skript version do you use? @iBlitzkriegi

**Comment by iBlitzkriegi** [comment]
I use: 
![image](https://user-images.githubusercontent.com/17624546/94712885-12890480-0318-11eb-9dc2-d0d300c519a3.png)

**Comment by killergotrekt** [comment]
it doesn't work within the latest version, **2.5 beta4**

**Comment by CarloDrift** [comment]
> it doesn't work within the latest version, **2.5 beta4**

Use a stable version of Skript, such as [2.5](https://github.com/SkriptLang/Skript/releases/download/2.5/Skript.jar).

**Comment by killergotrekt** [comment]
Well it works with dev36, why doesn't it work on 2.5.3? Closing since it works on 2.0.7
