### ISSUE TITLE
( SUGGESTION )  - New expression for Vixio-2.0.7.

### ISSUE THREAD

**Issue by TheyzGamer** [iBlitzkriegi/Vixio#270]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like add an expression for get a Discord account creation for a specified user.

**Describe alternatives you've considered**
None

**Additional context**
This expression would be added in this expression:
'[the] discord creation date[s] of %channel/guild/message/role/category/emote/attachment%'.

**Comment by iBlitzkriegi** [comment]
![image](https://user-images.githubusercontent.com/17624546/90319970-eaca1280-df0a-11ea-8fc8-2e97b9de3da5.png)

**Comment by TheyzGamer** [comment]
I would like an expression to get the date a Discord account was created and not the date when it joined this Discord server.
