### ISSUE TITLE
Bot can not DM user

### ISSUE THREAD

**Issue by TheDarkIceKing** [iBlitzkriegi/Vixio#271]
**Is your feature request related to a problem? Please describe.**
I tried to make the bot DM a user. However, when the user closes his/her dm or blocks the bot, a error is generated in console.

**Describe the solution you'd like**
Add a condition, to see if the bot is able to dm the user.

**Additional context**
![image](https://user-images.githubusercontent.com/67518900/90313342-07b31580-df0c-11ea-9146-f897bb428cfa.png)

**Comment by iBlitzkriegi** [comment]
I'm pretty sure you can't tell if you can message them without messaging them and getting the error. Will add a catch for the error though.
