### ISSUE TITLE
EffSendMessage {_variable} <none>

### ISSUE THREAD

**Issue by mashmarvin** [iBlitzkriegi/Vixio#272]
**Describe the bug**
Using a local variable (global works) in a send effect does not work.

**To Reproduce**
1. Insert following code into a discord command for example:
```
set {_arg} to arg 1
send "%{_arg}%" to channel named "discord-bots" with event-bot
send arg 1 to channel named "discord-bots" with event-bot
```
2. Execute the command with an argument
3. You will see, that the first message from the bot is `<none>` and the second matches your argument

**Information**
Skript version: 2.4.1
Vixio version: 2.0.4
Minecraft Version: Don't need a client for this...
Server software name and version: Spigot 1.12.2, specifically `CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Expected behavior**
Both messages from the bot should match the given argument.

**Comment by iBlitzkriegi** [comment]
This works perfectly fine for me, could be because of your skript version. I did hear something about how local variables were changed in recent versions of Skript. Could try setting it to a global variable to confirm that its skript. 
```
discord command test <text>:
	trigger:
		set {_test} to arg-1 
		send "%{_test}%" to event-channel with event-bot
```
![image](https://user-images.githubusercontent.com/17624546/90320052-abe88c80-df0b-11ea-9d4c-8763040731ad.png)

**Comment by mashmarvin** [comment]
Global variables work, yes. BUT, after testing this on likely all Skript versions down to 2.2-dev36 and none of them fixed it, i tried to out-comment the effects from vixio, like this:
```
set {_arg} to arg 1
# send "%{_arg}%" to channel named "discord-bots" with event-bot
send "%{_arg}%" to console
```
Reloaded and local variable worked flawless again. Not sure why, but Vixio syntax seems to break local variables. Maybe only on 1.12.2. Not sure what versions you used for testing this. If you want I can try with other Spigot versions

**Comment by DampfWaffel** [comment]
ello, to warp my problem that's kinda related, up.

```send(event-user, event-bot)
		
function send(u: user, b: bot):
	send "Never ever" to {_u} with {_b}
```
it send nothing. also tried it with channels, but same problemo.
