### ISSUE TITLE
Using function as prefixes.

### ISSUE THREAD

**Issue by SkyCraft78** [iBlitzkriegi/Vixio#273]
Hello !
I'm making a bot and I wanna configure the prefixe via a function.
Everything's good, but the function need to be in this form : 
```
discord command test:
    prefixes: "%prefixes()%"
```
But Skript said we can just remove `%` and `"` because it's already a text.
When I to that then : 
```
discord command test:
    prefixes: prefixes()
```
No error apear, but vixio took literally `prefixes()` as the prefixe, like `prefixes()test` for the command.

**Comment by SkyCraft78** [comment]
Then ?

**Comment by Pikachu920** [comment]
you could put a return type of object to suppress the warning

**Comment by TobyMinceraft** [comment]
Hey, I'm actually wondering if this is possible, as I'm trying to do something similar, myself. I'm still considered a noob at coding in Skript and with Vixio.

**Comment by SkyCraft78** [comment]
Okay thanks you Pikachu920 ^^
