### ISSUE TITLE
Request to add expression for Vixio.

### ISSUE THREAD

**Issue by TheyzGamer** [iBlitzkriegi/Vixio#275]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem. e.g. I'm still frustrated because there is a missing feature on the dates of creation of server rooms and members who have joined a server. I think the date of creation of a Discord account is clearly missing.

**Describe the solution you'd like**
This would be the addition of the "user" parameter to the following expression:
'[the] discord creation date[s] of %channel/guild/message/role/category/emote/attachment%'.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Tepoloco** [comment]
That would be good

**Comment by iBlitzkriegi** [comment]
You can get a users guild joining date and creation date via:
```
# arg-1 being a Member
set {_guildDate::*} to split "%join date of arg-1%" at " "
set {_discordDate::*} to split "%discord join date of arg-1%" at " "
```
Moreover, I have no clue what creation of server rooms means. You can already get a Guilds and Channels creation date with `discord creation date of`
