### ISSUE TITLE
On Reaction Remove not working in 2.0.7

### ISSUE THREAD

**Issue by GameNationBE** [iBlitzkriegi/Vixio#280]
![image](https://user-images.githubusercontent.com/72342955/95015361-afb3a800-064c-11eb-8433-c3e0baa9fc2a.png)
this is the embed made in 2.0.6, it fully works and removes the role.. works perfect

![image](https://user-images.githubusercontent.com/72342955/95015384-dbcf2900-064c-11eb-86f3-d5309074e291.png)
this is the exact same code in 2.0.7, doesnt remove the role and the "<none>" are placeholders i used %event-member% not variables

**Comment by killergotrekt** [comment]
use the format

**Comment by CarloDrift** [comment]
Did you enable the related gateway intent?

**Comment by GameNationBE** [comment]
yes
i enabled all gateways

**Comment by CarloDrift** [comment]
How?

**Comment by GameNationBE** [comment]
enable the guild message reactions intent
same for the others
