### ISSUE TITLE
Mistakes with music

### ISSUE THREAD

**Issue by MattyHD0** [iBlitzkriegi/Vixio#289]
**Describe the bug**
The music does not work, neither search nor play

**To Reproduce**

search youtube for arg-1 and store the results in {_results::*}
play {_results::1} in event-guild

**Information**
Skript version: 2.5-beta3
Vixio version: 2.0.7
Minecraft Version: 1.12.2
Server software name and version: Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Expected behavior**
The bot should play music

**Screenshots**
![image](https://user-images.githubusercontent.com/53882787/99907074-7ba64c00-2cb9-11eb-91c1-857bff46bb24.png)
![image](https://user-images.githubusercontent.com/53882787/99907095-98428400-2cb9-11eb-856e-1f46c7a20d52.png)
![image](https://user-images.githubusercontent.com/53882787/99907099-9f699200-2cb9-11eb-96b3-25cdf3c27cd3.png)

**Comment by k2enny** [comment]
Same problem

**Comment by FokaStudio** [comment]
same issue

**Comment by RedGamingTV** [comment]
Same... Any fix ever for music or just gonna keep music broken for a discord bot...?

**Comment by axilirate** [comment]
+1

**Comment by iBlitzkriegi** [comment]
Check the vixio discord for the latest fixed music version. A newer version will be released on github/spigot/skunity soon that will update it.
