### ISSUE TITLE
Improvements to online / bot documentation

### ISSUE THREAD

**Issue by DelayedGaming** [iBlitzkriegi/Vixio#291]
**Improvements to online / bot documentation**

The online / bot documentation comes in handly to understand the possibilities of Vixio can do, but it looks like the docs is missing one of the most important section, **event values**.

Each event has its own event values, a section contains event values in the docs helps a lot for users to understand an event. A small example is in the attached screenshot.
![20201205_181209](https://user-images.githubusercontent.com/72163224/101239959-e37f7c80-3726-11eb-8ef4-4aa9f8e40925.jpg)

**Comment by Olyno** [comment]
The online documentation is not related to Vixio directly. Please redirect your issue on the [online documentation website](https://github.com/Olyno/VixioSite)
