### ISSUE TITLE
Send message to user

### ISSUE THREAD

**Issue by JopGamer** [iBlitzkriegi/Vixio#302]
**Describe the bug**
Keď som sa pokúšal poslať správu cez bota do DM pomocov ID tak bot neposlal nič.

**Information**
Skript version: 2.5.2
Vixio version: 2.0.7
Minecraft Version: 1.12.2
Server software name and version: Spigot 1.12.2

**Expected behavior**
Sends a message to the DM

**Comment by iBlitzkriegi** [comment]
You must use the actual %user% object, you cannot send a message to a string of numbers. You could do it like so; `send "hello!" to user with id "1312312321321" with event-bot`
