### ISSUE TITLE
Removing and adding roles.

### ISSUE THREAD

**Issue by FluffyScab** [iBlitzkriegi/Vixio#312]
**Describe the bug**
When removing then adding a different role, it will add back the removed role.

**To Reproduce**
No steps but here is the code I'm using.
```
discord command ^verify <integer>:
    trigger:
        if {inUse::*} contains arg-1:
            send "&aYou have been verified!" to {%arg-1%::player}
            remove role with id "828384317984997377" from the roles of event-member
            set the discord nickname of event-member to {%arg-1%::username} with event-bot
            wait 1 second
            add role with id "828384381197615116" to the roles of event-member
            remove arg-1 from {inUse::*}
        else:
            reply with "This number is incorrect! Please enter the correct number."
```
I did try many other ways but they all turned out the same.

**Information**
Skript version: 2.5.3
Vixio version: 2.0.7
Minecraft Version: 1.16.4 
Server software name and version: Paper git-Paper-414

**Expected behavior**
I expected it to remove a role and add a different role with no issues.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/66979686/113523207-521dfb00-959e-11eb-9680-c9a42f5fcf4d.png)

**Comment by iBlitzkriegi** [comment]
Discord tends to get funky with adding and removing roles quickly, try adding a much larger wait period in-between everytime you update the roles.
