### ISSUE TITLE
Create an .txt file and save arg-1/event-message to file.txt  | finish - close it

### ISSUE THREAD

**Issue by FeuerzockerYT** [iBlitzkriegi/Vixio#315]
discord command createfile:
    create file named "file" as .txt

discord command addtofile <arg-1>:
    add arg-1 to file "file.txt"
    
    A .TXT file

**Comment by Reis3nder** [comment]
Is already possible

**Comment by FeuerzockerYT** [comment]
how can i do it?

**Comment by Reis3nder** [comment]
if file "... " exists:
     create file path "plugins/Skript/scripts/myAwesomeScript.sk" with text "command awesome:", "	trigger:" and "		broadcast ""Awesome!!!"""

**Comment by Reis3nder** [comment]
Search for Minecraft Skript Logs stem and you can see what I mean, it's the same thing with a logsystem

**Comment by FeuerzockerYT** [comment]
i just want his:

discord command +file:
    trigger:
        create file path "plugins/Skript/scripts/myAwesomeScript.sk" with text "command awesome:", " trigger:" and " broadcast ""Awesome!!!"""

**Comment by Reis3nder** [comment]
Yeah

**Comment by Reis3nder** [comment]
If you want I can help you, ad me on discord 'Holly - Kirito#3952'

**Comment by FeuerzockerYT** [comment]
error:
https://prnt.sc/118hxni

**Comment by Reis3nder** [comment]
I can send you the right script format in 20 minutes

**Comment by Reis3nder** [comment]
I helped I'm at discord

Can anyone close this issue?
