### ISSUE TITLE
Author of event-message

### ISSUE THREAD

**Issue by FeuerzockerYT** [iBlitzkriegi/Vixio#316]
discord command -author <arg-1>:
    trigger:
        reply with "Author of the message %arg-1" is: %author of arg-1%

on reaction add:
    emote = "thumbsup":
        add role with id "24174147" to roles of %author of event-message%

**Comment by iBlitzkriegi** [comment]
It's just %event-user%. To add roles to someone you'd use %event-member%. I.e `reply with "%event-user% is the author of %event-message%"`. For getting the author of a retrieved message you'd just use; 
![image](https://user-images.githubusercontent.com/17624546/115801907-dac4d580-a3ab-11eb-924a-653e909b3889.png)
