### ISSUE TITLE
on skript load

### ISSUE THREAD

**Issue by rafi67000** [iBlitzkriegi/Vixio#317]
hey i need help i made a startup script to log into vixio but the bot is not online
on skript load:
    login to user with token "XXXXXXXXXXXXXXXXXXXXXXX" with name "NAME"

**Comment by aril3721** [comment]
emm try this. **Maybe Work** 

on skript load:
       wait 1 minute
       login to user with token "XXXXXXXXXXXXXXXXXXXXXXX" with name "NAME"

**Comment by DampfWaffel** [comment]
would be nice. to share the latest.log with us

**Comment by MennoGamed** [comment]
Use:

on skript load:
	create vixio bot:
		enable the guild members intent
		enable the guild bans intent
		enable the guild emojis intent
		enable the guild invites intent
		enable the guild voice states intent
		enable the guild presences intent
		enable the guild messages intent
		enable the guild message reactions intent
		enable the direct messages intent
		enable the direct message reactions intent
		enable the direct message typing intent

		if "{@bot}" parsed as bot is not set: 
			login to "{@token}" with name "{@bot}"
			
This should be it.
