### ISSUE TITLE
Optional args in set embed author effect

### ISSUE THREAD

**Issue by User3794739** [iBlitzkriegi/Vixio#36]
Currently you are forced to specify every argument of the "Set Author Of Embed" effect so that it is e.g. not possible to create an embed without a hyperlink in the autor.

**Comment by iBlitzkriegi** [comment]
Are these issues for Vixio 1 or Vixio 2? Vixio 1 is no longer being worked on. Check the rewrite branch if you want to see Vixio 2.

**Comment by iBlitzkriegi** [comment]
This is already possible in Vixio 2. Check the rewrite branch.
