### ISSUE TITLE
Syntax conflict

### ISSUE THREAD

**Issue by Blueyescat** [iBlitzkriegi/Vixio#45]
```autohotkey
[the] members[s] of %guild/category%
%guild/category%'[s] members[s]
```
conflicts with Skript's region members syntax:
```autohotkey
(all|the|) (0¦members|1¦owner[s]) of [[the] region[s]] %regions%
```
If you use a variable for the expression.

The syntax should be `[[the] (guild|category)] %guild/category%`, also other syntaxes should be like this too.

Also don't forget to fix the `s[s]` thing, and this syntax shouldn't allow using `member of`.

**Comment by TrademarkTM** [comment]
Also, there are conflicts with Skellet's book syntaxes (title, author) and skQuery's new line.

`%nl%` causes this:
https://i.imgur.com/roKsQEk.png
