### ISSUE TITLE
fields of embed bug with the S

### ISSUE THREAD

**Issue by AlexLew95** [iBlitzkriegi/Vixio#47]
This bug was already present in releases before and has not fixed. Just in the syntax:
```vb
add split field named "Field Name" with value "Field value" to fields of embed
```
It will not work because ``field`` has a S and we got a error:

```
members of the embed can't have anything added to it
```

But with:
```vb
add split field named "Field Name" with value "Field value" to field of embed
``` 
There are no problem and no error and code will work good.

**Comment by Pikachu920** [comment]
not vixio's fault, and adding to the fields expression is not the recommended way anyway (use add {_field} to the embed)
