### ISSUE TITLE
Bungeecord Suggestion

### ISSUE THREAD

**Issue by Shane1199** [iBlitzkriegi/Vixio#6]
If I understand correctly, this doesn't support Bungeecord. So I am suggesting that it be made compatible so I could get all the chat sent/received from all of the servers within Bungeecord.

**Comment by itismejoey** [comment]
You can easily do this by putting the same (with some formatting changes) script on each server.

**Comment by Shane1199** [comment]
That is very true. Are there any plans on supporting 1.7.10 then? I have a Pixelmon 1.7.10 server, Pixelmon servers keep their playerbases in most their versions.

**Comment by iBlitzkriegi** [comment]
Does it not already support 1.7.10?
