### ISSUE TITLE
Add "%bot%" and "[in %-guild%]" in expression voice channel of %members%

### ISSUE THREAD

**Issue by AlexLew95** [iBlitzkriegi/Vixio#60]
Currently, we can't use ``if voice channel of event-bot is set`` for example. Can you accept bot's expression please?

Thanks you

Current expression:

``[the] voice[(-| )] channel[s] of %members%,%members%'[s] voice[(-| )] channel[s]'``

**Comment by AlexLew95** [comment]
Not really @Pikachu920 :
``event-types.bot is not a types.member``

```
{*}------Vixio debug------{*}
Minecraft: git-Spigot-3d850ec-809c399 (MC: 1.12.2)
Server: 1.12.2-R0.1-SNAPSHOT
Vixio: 2.0.0-dev9
Skript: 2.2-dev36
{*}---------------------{*}
```

**Comment by Pikachu920** [comment]
you must provide a guild

**Comment by AlexLew95** [comment]
So, I tried with ``in %guild%`` and it works.
Also, ``in %guild%`` is not in Syntaxes.txt, and not in this syntax. Need correct this file, really.

**Comment by AlexLew95** [comment]
"``%user% in %guild%`` returns a member
Just adding a bot wouldn't help because a bot isn't a member" answered by Blitz, I close my issue, thanks for helping
