### ISSUE TITLE
Syntax conflict with voice channel of

### ISSUE THREAD

**Issue by AlexLew95** [iBlitzkriegi/Vixio#63]
Syntax conflict between
```
[the] voice(-| )channel[s] of %guild/category%"
%guild/category%'[s] voice(-| )channel[s]
```
and
```
[the] voice[(-| )] channel[s] of %members%"
%members%'[s] voice[(-| )] channel[s]
```
Debug:
```
{*}------Vixio debug------{*}
Minecraft: git-Spigot-3d850ec-809c399 (MC: 1.12.2)
Server: 1.12.2-R0.1-SNAPSHOT
Vixio: 2.0.0
Skript: 2.2-dev36
{*}---------------------{*}
```

**Comment by iBlitzkriegi** [comment]
Can I have the code that you used to prove this so?

**Comment by AlexLew95** [comment]
```vb
discord command test:
	prefixes: -
	trigger:
		add voice-channels of event-guild to {_channels::*}
		add voice-channels of event-member to {_channels::*}
		reply with "%{_channels::*}%"
```
This code will return all voice channels in your guild, but not the channel of the event-member

**Comment by Snow-Pyon** [comment]
Just merge them, no reason to have them separated.

**Comment by iBlitzkriegi** [comment]
Except for the fact that I want voice channel of member to return a single value while voicechannels of guild/category needs to return a list. I was messing with it last night with Pika, not sure how I'll handle it yet

**Comment by iBlitzkriegi** [comment]
This was just fixed, now there are two syntaxes. The main difference being the "s", `voicechannel of %member%` and `voicechannels of guild/category`
