### ISSUE TITLE
2 Bugs in Vixio 2

### ISSUE THREAD

**Issue by Bartuzen** [iBlitzkriegi/Vixio#64]
~~1- Emotions "track_previous" and "track_next" is not working.
`add reaction "track_previous", "arrow_backward", "arrow_forward" and "track_next" to {_msg} with event-bot`
When code is triggered, track ones give unkown emote and doesn't work while arrows and anything else I write work fine.~~

2-That one is kinda long. I'll describe it with an expamle. Let's think about an embed that a bot has sent. And it contains lines starting with "**1.**", "**2.**" and "**3.**" etc. (They are **bold** which is important.) When I edit embed in reaction add event, it should become like this: "**4.**", "**5.**" and "**6.**". But instead, some random numbers are being shown. Like this one:
[http://prntscr.com/k6rkac](url)
It happens only when numbers are in bold. But I think something else that I don't know also triggers the bug.

**Comment by AlexLew95** [comment]
About your first "bug", that's not a bug. Many emojis names are not the same as on discord. In other words, they sometimes change. To check these names, just use the following code:
```vb
reaction added:
    send name of event-emote to console
```
About your second bug, I doubt it's a bug, too, but I think more of a problem in your values. We need to know the code you used to edit your embed and set your variables.

**Comment by Bartuzen** [comment]
Thanks for info about first bug. I understand you think it is about variables, but that is because I forgot to add something. When I reply with the new created embed, it works fine. Itis bugy only if I replace it with an existing one. If it is still required, I can still send my code.

**Comment by Bartuzen** [comment]
I don't know how but currently, it looks like it got fixed magically. I kept editing code so maybe I changed something to make it work. I am still sure it is not about my variables. If it happens again, I will send code.

**Comment by Bartuzen** [comment]
I got it again. I guess it happens if values in list variable are different.
https://imgur.com/a/BoDVFDQ
I will send code as soon as possible.
