### ISSUE TITLE
Some Requests

### ISSUE THREAD

**Issue by Bartuzen** [iBlitzkriegi/Vixio#66]
An event called when a track is added to queue:
`on track added to queue seen by "bot"`
Request a song by player:
`play "blala" requested by event-user
requester of event-track`
Member in voice channel:
`members in voice channel "blabla"`
Duration of a track from Yt or Sc link:
`duration of track from url "https://blabla...."`

**Comment by iBlitzkriegi** [comment]
Most of this has been added or was left up to the user.
