### ISSUE TITLE
Soundcloud cookie issue

### ISSUE THREAD

**Issue by PhilFinachi** [iBlitzkriegi/Vixio#7]
https://pastebin.com/mya9dbNq
when playing any soundcloud link

**Comment by tutur1004** [comment]
Sound Cloud need to be registered for some sounds, of course bot can't be registered

**Comment by PhilFinachi** [comment]
@tutur1004 the track is both public and not premium.

**Comment by tutur1004** [comment]
Yes me too, but sometimes SoundCloud block some sounds for bots players, it's same for all bots !
