### ISSUE TITLE
Problem with plugin

### ISSUE THREAD

**Issue by djmanbr** [iBlitzkriegi/Vixio#74]
Hello everyone!

I made a bot with this addon/plugin, it works correctly in localhost, but when I move it to my server the bot log in but doesn't work any command or doesn't show the playing status.

Anyone know something about that? May be ports?

**Comment by iBlitzkriegi** [comment]
This would not be caused by Vixio, most likely something specific to the server you're trying to host the bot on. But seeing as no errors have been provided there is no way to reproduce this issue.
