### ISSUE TITLE
Weird Bug That Occurs When Editing Embed

### ISSUE THREAD

**Issue by Bartuzen** [iBlitzkriegi/Vixio#78]
https://pastebin.com/tK5Ejcj3
After editing the embed, embed description should be like this:
**acbca:** asda
as it says so in the code. But, unlike that, it's description it getting buggy. Like this example:
https://i.imgur.com/AF7Rydd.png
It doesn't reset previous embed at all. It happens only if code has markdown like bold text.

**Comment by iBlitzkriegi** [comment]
I never could recreate this.
