### ISSUE TITLE
Issues when playing some youtube links

### ISSUE THREAD

**Issue by PhilFinachi** [iBlitzkriegi/Vixio#8]
https://pastebin.com/6aYG4nM7

song in question:
https://www.youtube.com/watch?v=Uno7f5IGAPI

**Comment by iBlitzkriegi** [comment]
The version of something called GLIBC your host uses is severely updated. Make a ticket with them in order to have them update to at least GLIBC/LIBC 2.15+. You're host uses 2.5....Released 13 years ago 🤐
