### ISSUE TITLE
Conflict with skript or another addon --> [the] owner[s] of %guilds%

### ISSUE THREAD

**Issue by AlexLew95** [iBlitzkriegi/Vixio#82]
**Describe your problem:**
Recently, I've been getting an error with the following syntax:
``[the] owner[s] of %guilds%``
So I think it conflicts with another syntax

**Solution to correct the problem:**
Use the syntax:
``[the] owners of %guilds%``

**Code:**
```vb
discord command test:
	prefixes: !
	trigger:
		set {_guild} to event-guild
		owner of {_guild} is event-member
		broadcast "yolo"
```
**Error:**
``Can't compare a player with a types.member``

**Addons:**
- Skript 2.2-dev37c
- skript-yaml 1.2.4
- skUtilities 0.9.2
- Vixio 2.0.0
- SkQuery 3.6.1-Lime
- skript-mirror 0.18.0

**Debug mode message:**
```
{*}------Vixio debug------{*}
Minecraft: git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2)
Server: 1.12.2-R0.1-SNAPSHOT
Vixio: 2.0.0
Skript: 2.2-dev37c
{*}---------------------{*}
```

**Comment by iBlitzkriegi** [comment]
It'd be nice if you found out which addon actually caused it instead of leaving me to remake your environment

**Comment by AlexLew95** [comment]
The conflict comes from SkQuery 3.6.1-Lime
