### ISSUE TITLE
2 Requests

### ISSUE THREAD

**Issue by Bartuzen** [iBlitzkriegi/Vixio#88]
```vb
verification level of %guild%
creation date of %guild%
```

**Comment by iBlitzkriegi** [comment]
These have since been added; Creation date: https://github.com/iBlitzkriegi/Vixio/commit/72e57eaaea26e2f007c475e454df814526a15463 and verification level: https://github.com/iBlitzkriegi/Vixio/commit/6b6c7922c83cf4385adaca2f686a3bcb7fd05af5
