### ISSUE TITLE
Issue playing "topic" youtube videos

### ISSUE THREAD

**Issue by PhilFinachi** [iBlitzkriegi/Vixio#9]
error:
WARN [Skript] Something's gone...So wrong...Oh so very wrong. I messed up loading apparently...?
song in question:
https://www.youtube.com/watch?v=KDbVmD8Gatg

**Comment by iBlitzkriegi** [comment]
Attempt to re-load the video, it may have had issues with it due to it being unlisted/privated? I mean, not every song in the world can work. Lavaplayer isn't perfect.
