### ISSUE TITLE
There is a problem with silencing a player.

### ISSUE THREAD

**Issue by xNightCloud** [iBlitzkriegi/Vixio#91]
There is a problem with silencing a player.

`discord command $mute:
	bots: {@NAME}
	trigger:
		mute event-user in event-guild with event-bot
		reply with "Mute...`

**Comment by Magical-Developer** [comment]
[
![image](https://user-images.githubusercontent.com/42165949/45583654-dfa97a80-b8ce-11e8-93fd-6f355955c2f9.png)
](url)

**Comment by iBlitzkriegi** [comment]
I need the full error, and do take note that this effect is for muting a member inside of a voice channel.

**Comment by iBlitzkriegi** [comment]
Closing due to lack of response or updates.
