### ISSUE TITLE
Make storing embeds per user 

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#93]
I'm not sure if this is a bug but, i've noticed and nobody has addressed it yet but, if you were to store a embed for like reactions etc, and a user clicks the reaction it works, right? Well if you typed the command, and it stored the embed, and then someone else typed the command while you havent clicked the reaction yet, it will void the previous embed. Is there any way you can store the embeds to the memory, or until reload or restart it wipes? Thanks Ender.

**Comment by Pikachu920** [comment]
this is just an issue with how you handle your variables

**Comment by EnderDev** [comment]
I do {var::%id of event-user%} and sometimes {var::%id of event-user%::%id of event-channel%}, but it gets overwritten every time another user types the command.

**Comment by Pikachu920** [comment]
same thing

**Comment by EnderDev** [comment]
so what am I doing wrong

**Comment by EnderDev** [comment]
uhm, my issue wasn't answered could it be answered please

**Comment by iBlitzkriegi** [comment]
It was determined that it was not a Vixio issue. If you'd like to seek support for your issues then refer to the Vixio guild, as to not spam the addon meta channel.
