### ISSUE TITLE
id of event-channel become another id

### ISSUE THREAD

**Issue by AlexLew95** [iBlitzkriegi/Vixio#96]
**Explains:**
In the code below, "id of event-user" becomes another id in the list. For example, if the id of the user A is 1, and the id of the user B is 2, if user B join after the user A, the id of the user B will be 1 and not 2.

**Code to reproduce it:**
```vb
reaction added:
	remove id of event-user from {queue::*}
	add id of event-user to {queue::*}
	set {_found} to false
	while {_found} is false:
		wait 3 seconds
		loop {queue::*}:
			loop-value != id of event-user
			set {_found} to true
			
	reply with id of event-user
	clear {queue::*}
```

**Debug;**
Skript; dev37c
Spigot: 1.12.2
Vixio: 2.0pre02

**Comment by iBlitzkriegi** [comment]
I'm not able to reproduce this behavior, I'm unsure of what your check inside of the loop is meant to do so I modified it to be:
```
reaction added:
	remove id of event-user from {queue::*}
	add id of event-user to {queue::*}
	set {_found} to false
	while {_found} is false:
		wait 3 seconds
		loop {queue::*}:
			broadcast "%loop-value%"
			if loop-value is id of event-user:
				set {_found} to true
			
	reply with id of event-user
	clear {queue::*}
``` 
And it worked as intended.

**Comment by iBlitzkriegi** [comment]
I was never able to reproduce this bug.
